fields:
# sheet: Outgunned
# include: include/header.twig
# include: include/data.twig
### general
  # row
    # col: col-12 col-lg-8
      # card: personal: Personal
        # card-body
          # table
          # width: 30%
  name:
    label: "Character Name"
    input: string
  player:
    label: "Player Name"
    input: string
  level:
    label: "Level"
    input: integer
    placeholder: "eg. 1"
### Backstory
  ancestry:
    label: "Ancestry"
    input: string
    placeholder: "eg. Human"
  culture:
    label: "Culture"
    input: text
    rows: 3
    placeholder: "eg. Reshi, Alethi"
  paths:
    label: "Paths"
    input: text
    rows: 3
    placeholder: "eg. Agent"
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-lg-4 hidden-xs hidden-sm hidden-md d-none d-lg-block
      # card: portrait
        # card-body
  imageid:
    label: "Portrait"
    render: image
    input: integer
    min: 0
    placeholder: "WA Image ID"
        # /card-body
      # /card
    # /col
  # /row
### attributes
  # row
    # col: col-12 col-md-4
      # card: attributes: Physical
        # card-body
          # row
            # col: col-12 col-md-4
### strength
              # iter: 1:1
  att value:
    label: "{{att[id-1]}}"
    input: integer
    min: 0
    max: 5
              # /iter
            # /col
            # col: col-12 col-md-4
  defense_physical:
    label: "Defense"
    description: "Defense modifier through items, spells, etc."
    input: integer
  text:
    label: "{{ variables.att_value_001|default + variables.att_value_002|default + variables.defense_physical|default + 10}}"
            # /col
            # col: col-12 col-md-4
### speed
              # iter: 2:2
  att value:
    label: "{{att[id-1]}}"
    input: integer
    min: 0
    max: 5
              # /iter
            # /col
          # /row
        # /card-body
      # /card
      # card: health
        # card-body
  health mod:
    label: "Health Modifier"
    input: integer
    description: "Health modifier through items, spells, etc."
  health curr:
    label: "Current"
    input: integer
    description: "Maximum is 10 + STR + modifier"
  deflect:
    label: "Deflect"
    input: integer
        # /card-body
      # /card
      # card: skills
        # card-body
          # table
  ### skills
            # iter: 1:6
    # width: 50%
    # dots: 5
  sk value:
    label: "{{skill_list[id-1][0]}}"
    input: integer
    min: 0
    max: 5
            # /iter
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4
      # card: attributes: Cognitive
        # card-body
### intellect
          # row
            # col: col-12 col-md-4
              # iter: 3:3
  att value:
    label: "{{att[id-1]}}"
    input: integer
    min: 0
    max: 5
              # /iter
            # /col
            # col: col-12 col-md-4
  defense_cognitive:
    label: "Defense"
    description: "Defense modifier through items, spells, etc."
    input: integer
  text:
    label: "{{ variables.att_value_003|default + variables.att_value_004|default + variables.defense_cognitive|default + 10}}"
            # /col
            # col: col-12 col-md-4
### willpower
              # iter: 4:4
  att value:
    label: "{{att[id-1]}}"
    input: integer
    min: 0
    max: 5
              # /iter
            # /col
          # /row
        # /card-body
      # /card
      # card: focus
        # card-body
  focus mod:
    label: "Focus Modifier"
    input: integer
    description: "Focus modifier through items, spells, etc."
  focus curr:
    label: "Current"
    input: integer
    description: "Maximum is 2 + WIL + modifier"
        # /card-body
      # /card
      # card: skills
        # card-body
          # table
  ### skills
            # iter: 7:12
    # width: 50%
    # dots: 5
  sk value:
    label: "{{skill_list[id-1][0]}}"
    input: integer
    min: 0
    max: 5
            # /iter
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4
      # card: attributes: Spiritual
        # card-body
### awareness
          # row
            # col: col-12 col-md-4
              # iter: 5:5
  att value:
    label: "{{att[id-1]}}"
    input: integer
    min: 0
    max: 5
              # /iter
            # /col
            # col: col-12 col-md-4
  defense_spiritual:
    label: "Defense"
    description: "Defense modifier through items, spells, etc."
    input: integer
  text:
    label: "{{ variables.att_value_005|default + variables.att_value_006|default + variables.defense_spiritual|default + 10}}"
            # /col
            # col: col-12 col-md-4
### presence
              # iter: 6:6
  att value:
    label: "{{att[id-1]}}"
    input: integer
    min: 0
    max: 5
              # /iter
            # /col
          # /row
        # /card-body
      # /card
      # card: investiture
        # card-body
  investiture max:
    label: "Investiture Pool"
    input: integer
    description: "Investiture modifier through items, spells, etc."
  investiture curr:
    label: "Current"
    input: integer
        # /card-body
      # /card
      # card: skills
        # card-body
          # table
  ### skills
            # iter: 13:18
    # width: 50%
    # dots: 5
  sk value:
    label: "{{skill_list[id-1][0]}}"
    input: integer
    min: 0
    max: 5
            # /iter
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-3
  text:
    label: "Lifting Capacity: {{lcap|default}}"
    # /col
    # col: col-12 col-md-3
  text:
    label: "Movement Rate: {{mr|default}}"
    # /col
    # col: col-12 col-md-3
  text:
    label: "Recovery Die: {{rdie|default}}"
    # /col
    # col: col-12 col-md-3
  text:
    label: "Senses Range: {{senser|default}}"
    # /col
  # /row
  # row
    # col: col-12 col-md-6
      # card: conditions: Conditions
        # card-body
  conditions:
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: expertises: Expertises
        # card-body
  expertises:
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-6
      # card: weapons: Weapons
        # card-body
          # table: horiz
            # iter: 6
  weapon type:
    label: "Type"
    input: string
    placeholder: "eg. Knife "
  weapon skill:
    label: "Skill"
    input: select
    options:
      dummy1: dummy1
      dummy2: dummy2
      dummy3: dummy3
  weapon damage:
    label: "Damage"
    input: string
    placeholder: "eg. 1d6 keen"
  weapon range:
    label: "Range"
    input: string
    placeholder: "eg. Melee"
  weapon traits:
    label: "Traits"
    input: string
    placeholder: "eg. Thrown, Quickdraw"
  # width: 60px
  weapon weight:
    label: "Weight"
    input: integer
    description: "Weight in lb"
  # width: 50px
  weapon active:
    label: "Active"
    input: checkbox
    description: "Item worn / used"
            # /iter
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: talents: Talents
        # card-body
          # table
            # iter: 10
  talent:
    label: "Talent {{id}}"
    input: string
  talent desc:
    label: "Description"
    input: text
    rows: 3
            # /iter
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: goals: Goals
        # card-body
  purpose:
    label: "Purpose"
    input: text
    rows: 3
  obstacle:
    label: "Obstacle"
    input: text
    rows: 3
          # table: horiz
            # iter: 10
  goal:
    label: "Goal"
    input: string
  goal prog 01:
    input: checkbox
  goal prog 02:
    input: checkbox
  goal prog 03:
    input: checkbox
            # /iter
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: appearance: Appearance
        # card-body
  appearance:
    input: text
    rows: 3
        # /card-body
      # /card
      # card: equipment: Equipment
        # card-body
          # table: horiz
            # iter: 20
  equip name:
    label: "Name"
    input: string
    description: "Item name"
  # width: 60px
  equip quantity:
    label: "#"
    input: integer
    description: "Quantity"
  # width: 60px
  equip weight:
    label: "Weight"
    input: integer
    description: "Weight in lb"
  # width: 50px
  equip active:
    label: "Active"
    input: checkbox
    description: "Item worn / used"
            # /iter
          # /table
  text:
    label: "Capacity: {{carried|default(0)}}/{{ccap|default }} lb"
  spheres:
    label: "Spheres"
    input: string
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: connections: Connections
        # card-body
  connections:
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: notes: Notes
        # card-body
  notes:
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
  # /row
# /sheet