### this yml is for the yml2sheet script, it's slighty different from the wa version (checkboxes)
# sheet: blood and doom
fields:
  # row
    # col: col-12 col-md-7
      # card: personal: Personal Information
        # card-body
          # table
  name:
    label: "Name"
    input: string
    placeholder: "Name of the hero"
    description: "This is the name of your hero."
    required: true
  species:
    label: "Species"
    input: string
  class:
    label: "Class"
    input: string
  career:
    label: "Career"
    input: string
  career level:
    label: "Career Level"
    input: string
  career path:
    label: "Career Path"
    input: string
  status:
    label: "Status"
    input: string
  age:
    label: "Age"
    input: string
  height:
    label: "Height"
    input: string
  hair:
    label: "Hair"
    input: string
  eyes:
    label: "Eyes"
    input: string
          # /table
        # /card-body
      # /card
    # /col
    # col: col-5 col-lg-5 hidden-xs hidden-sm hidden-md d-none d-lg-block
      # card: portrait: Portrait
        # card-body
  portrait:
    label: ""
    input: integer
    render: image
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-6
      # card: characteristics: Characteristics
        # card-body
          # table: horiz
  att ws label:
    label: "ws"
  att bs label:
    label: "bs"
  att s label:
    label: "s"
  att t label:
    label: "t"
  att i label:
    label: "i"
  att ag label:
    label: "ag"
  att dex label:
    label: "dex"
  att int label:
    label: "int"
  att wp label:
    label: "wp"
  att fel label:
    label: "fel"
          # /table
          # table: horiz
  att ws ini:
    input: string
  att bs ini:
    input: string
  att s ini:
    input: string
  att t ini:
    input: string
  att i ini:
    input: string
  att ag ini:
    input: string
  att dex ini:
    input: string
  att int ini:
    input: string
  att wp ini:
    input: string
  att fel ini:
    input: string
          # /table
          # table: horiz
  att ws adv:
    input: string
  att bs adv:
    input: string
  att s adv:
    input: string
  att t adv:
    input: string
  att i adv:
    input: string
  att ag adv:
    input: string
  att dex adv:
    input: string
  att int adv:
    input: string
  att wp adv:
    input: string
  att fel adv:
    input: string
          # /table
          # table: horiz
  att ws curr:
    input: string
  att bs curr:
    input: string
  att s curr:
    input: string
  att t curr:
    input: string
  att i curr:
    input: string
  att ag curr:
    input: string
  att dex curr:
    input: string
  att int curr:
    input: string
  att wp curr:
    input: string
  att fel curr:
    input: string
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: resilience: Resilience
        # card-body
          # table
  resilience:
    label: "Resilience"
    input: string
  resolve:
    label: "Resolve"
    input: string
  motivaton:
    label: "Motivation"
    input: string
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: experience: Experience
        # card-body
          # table
  xp curr:
    label: "Current"
    input: string
  xp spent:
    label: "Spent"
    input: string
  ### xp_total = xp_curr + xp_spent
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: movement: Movement
        # card-body
          # table
  movement:
    label: "Movement"
    input: string
  walk:
    label: "Walk"
    input: string
  run:
    label: "Run"
    input: string
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-6
      # card: basic skills: Basic Skills
        # card-body
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: basic skills: Basic Skills
        # card-body
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: group and advanced skills: Group & Advanced Skills
        # card-body
          # table: horiz
            # iter: 1
  gaskill name label:
    label: "Name"
  gaskill char label:
    label: "Characteristic"
  gaskill adv label:
    label: "Adv"
  gaskill skill label:
    label: "Skill"
            # /iter
          # /table
          # table: horiz
            # iter: 20
  gaskill name:
    input: string
  gaskill char:
    input: string
  gaskill adv:
    input: string
  gaskill skill:
    input: string
            # /iter
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: talents: Talents
        # card-body
          # table: horiz
            # iter: 1
  talent name label:
    label: "Talent Name"
  talent taken label:
    label: "Times taken"
  talent desc label:
    label: "Description"
            # /iter
          # /table
          # table: horiz
            # iter: 20
  talent name:
    input: string
  talent taken:
    input: string
  talent desc:
    input: string
            # /iter
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: ambitions: Ambitions
        # card-body
  amb short:
    label: "Short Term"
    input: text
    rows: 3
  amb long:
    label: "Long Term"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: party: Party
        # card-body
  party name:
    label: "Party Name"
    input: string
  party short:
    label: "Short Term"
    input: text
    rows: 3
  party long:
    label: "Long Term"
    input: text
    rows: 3
  party members:
    label: "Members"
    input: string
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-8
      # card: armour: Armour
        # card-body
          # table: horiz
            # iter: 1
  armour name label:
    label: "Name"
  armour loc label:
    label: "Locations"
  armour enc label:
    label: "Enc"
  armour ap label:
    label: "AP"
  armour qual label:
    label: "Qualities"
            # /iter
          # /table
          # table: horiz
            # iter: 5
  armour name:
    input: string
  armour loc:
    input: string
  armour enc:
    input: string
  armour ap:
    input: string
  armour qual:
    input: string
            # /iter
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4
      # card: armour points: Armour Points
        # card-body
          # table
  arm head:
    label: "Head (01-09)"
    input: string
  arm larm:
    label: "Left arm (10-24)"
    input: string
  arm rarm:
    label: "Right arm (25-44)"
    input: string
  arm body:
    label: "Body (54-79)"
    input: string
  arm lleg:
    label: "Left leg (80-89)"
    input: string
  arm rleg:
    label: "Right leg (90-00)"
    input: string
  arm shield:
    label: "Shield"
    input: string
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-5
      # card: trappings: Trappings
        # card-body
          # table: horiz
  trapping label:
    label: "Name"
  trapping enc label:
    label: "Enc"
          # /table
          # table: horiz
            # iter: 20
  trapping:
    label: ""
    input: string
  trapping enc:
    label: ""
    input: string
            # /iter
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-7
      # card: psychology: Psychology
        # card-body
  psychology:
    label: ""
    input: text
    rows: 3
        # /card-body
      # /card
      # card: corruption: Corruption & Mutation
        # card-body
  corruption:
    label: ""
    input: text
    rows: 3
        # /card-body
      # /card
      # row
        # col: col-12 col-md-6
          # card: wealth: Wealth
            # card-body
              # table
  wealth d:
    label: "D"
    input: string
  wealth ss:
    label: "SS"
    input: string
  wealth gc:
    label: "GC"
    input: string
              # /table
            # /card-body
          # /card
          # card: wounds: Wounds
            # card-body
              # table
  wounds sb:
    label: "SB"
    input: string
  wounds tbx2:
    label: "TBx2"
    input: string
  wounds wpb:
    label: "WPB"
    input: string
  wounds hardy:
    label: "Hardy"
    input: string
  wounds wounds:
    label: "Wounds"
    input: string
  wounds desc:
    label: "Details"
    input: text
    rows: 3
              # /table
            # /card-body
          # /card
        # /col
        # col: col-12 col-md-6
          # card: encumbrance: Encumbrance
            # card-body
              # table
  enc weapons:
    label: "Weapons"
    input: string
  enc armour:
    label: "Armour"
    input: string
  enc Trapping:
    label: "Trappings"
    input: string
  enc max enc:
    label: "Max Enc."
    input: string
      ### total 
              # /table
            # /card-body
          # /card
          # card: fate: Fate
            # card-body
              # table
  fate:
    label: "Fate"
    input: string
  fortune:
    label: "Fortune"
    input: string
              # /table
            # /card-body
          # /card
        # /col
      # /row
    # /col
  # /row
  # row
    # col: col-12 col-md-6
      # card: weapons: Weapons
        # card-body
          # table: horiz
            # iter: 1
  weap name label:
    label: "Name"
  weap group label:
    label: "Group"
  weap enc label:
    label: "Enc"
  weap rng label:
    label: "Range/Reach"
  weap dmg label:
    label: "Damage"
  weap qual label:
    label: "Qualities"
            # /iter
          # /table
          # table: horiz
            # iter: 8
  weap name:
    input: string
  weap group:
    input: string
  weap enc:
    input: string
  weap rng:
    input: string
  weap dmg:
    input: string
  weap qual:
    input: string
            # /iter
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: spells: Spells & Prayers
        # card-body
          # table: horiz
            # iter: 1
  spell name label:
    label: "Name"
  spell cn label:
    label: "CN"
  spell rng label:
    label: "Range"
  spell tgt label:
    label: "Target"
  spell dur label:
    label: "Duration"
  spell effect label:
    label: "Effect"
            # /iter
          # /table
          # table: horiz
            # iter: 8
  spell name:
    input: string
  spell cn:
    input: string
  spell rng:
    input: string
  spell tgt:
    input: string
  spell dur:
    input: string
  spell effect:
    input: string
            # /iter
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-12
      # card: notes: Notes
        # card-body
  notes:
    label: ""
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
  # /row
# /sheet