fields:
  name:
    label: "name"
    input: string
    description: "Hero Name"
  player name:
    label: "player name"
    input: string
    description: "Player Name"
  species:
    label: "species"
    input: string
    description: "Species"
  gender:
    label: "gender"
    input: string
    description: "Gender"
  profession:
    label: "profession"
    input: string
    description: "Profession"
  career:
    label: "career"
    input: string
    description: "Career"
  pattributes:
    label: "pattributes"
    input: string
    description: "Attributes"
  age:
    label: "age"
    input: string
    description: "Age"
  height:
    label: "height"
    input: string
    description: "Height"
  weight:
    label: "weight"
    input: string
    description: "Weight"
  appearance:
    label: "appearance"
    input: string
    description: "Appearance"
  allegiance:
    label: "allegiance"
    input: string
    description: "Allegiance"
  social status:
    label: "social status"
    input: string
    description: "Social Status"
  setting:
    label: "setting"
    input: string
    description: "Setting"
  gamemaster:
    label: "gamemaster"
    input: string
    description: "Gamemaster"
  last resorts:
    label: "last resorts"
    input: string
    description: "Last Resorts"
  last resort cost:
    label: "last resort cost"
    input: string
    description: "Last Resort Cost"
  portrait:
    label: "portrait"
    input: integer
    description: "Portrait"
    render: image
  strength:
    label: "strength"
    input: string
    description: "Strength"
  strength untr:
    label: "strength untr"
    input: string
    description: "Untrained"
  dexterity:
    label: "dexterity"
    input: string
    description: "Dexterity"
  dexterity untr:
    label: "dexterity untr"
    input: string
    description: "Untrained"
  constitution:
    label: "constitution"
    input: string
    description: "Constitution"
  constitution untr:
    label: "constitution untr"
    input: string
    description: "Untrained"
  intelligence:
    label: "intelligence"
    input: string
    description: "Intelligence"
  intelligence untr:
    label: "intelligence untr"
    input: string
    description: "Untrained"
  will:
    label: "will"
    input: string
    description: "Will"
  will untr:
    label: "will untr"
    input: string
    description: "Untrained"
  personality:
    label: "personality"
    input: string
    description: "Personality"
  personality untr:
    label: "personality untr"
    input: string
    description: "Untrained"
  acs marginal:
    label: "acs marginal"
    input: string
    description: "Marginal"
  acs ordinary:
    label: "acs ordinary"
    input: string
    description: "Ordinary"
  acs good:
    label: "acs good"
    input: string
    description: "Good"
  acs amazing:
    label: "acs amazing"
    input: string
    description: "Amazing"
  acs die:
    label: "acs die"
    input: string
    description: "Die"
  acs actions:
    label: "acs actions"
    input: string
    description: "Actions/Round"
  cmr sprint:
    label: "cmr sprint"
    input: string
    description: "Sprint"
  cmr run:
    label: "cmr run"
    input: string
    description: "Run"
  cmr walk:
    label: "cmr walk"
    input: string
    description: "Walk"
  cmr easy swim:
    label: "cmr easy swim"
    input: string
    description: "Easy Swim"
  cmr swim:
    label: "cmr swim"
    input: string
    description: "Swim"
  cmr glide:
    label: "cmr glide"
    input: string
    description: "Glide"
  cmr fly:
    label: "cmr fly"
    input: string
    description: "Fly"
  dur stun:
    label: "dur stun"
    input: string
    description: "Stun"
  dur wound:
    label: "dur wound"
    input: string
    description: "Wound"
  dur fatigue:
    label: "dur fatigue"
    input: string
    description: "Fatigue"
  dur mortal:
    label: "dur mortal"
    input: string
    description: "Mortal"
  armor:
    label: "armor"
    input: string
    description: "Armor"
  armor li:
    label: "armor li"
    input: string
    description: "LI"
  armor hi:
    label: "armor hi"
    input: string
    description: "HI"
  armor en:
    label: "armor en"
    input: string
    description: "EN"
  special abilities:
    label: "special abilities"
    input: text
    description: "Special Abilities"
    rows: 3
  perks:
    label: "perks"
    input: text
    description: "Perks"
    rows: 3
  flaws:
    label: "flaws"
    input: text
    description: "Flaws"
    rows: 3
  other:
    label: "other"
    input: text
    description: "Other"
    rows: 3
  att name 001:
    label: "att name 001"
    input: string
    description: "Name"
  att name 002:
    label: "att name 002"
    input: string
    description: "Name"
  att name 003:
    label: "att name 003"
    input: string
    description: "Name"
  att name 004:
    label: "att name 004"
    input: string
    description: "Name"
  att name 005:
    label: "att name 005"
    input: string
    description: "Name"
  att name 006:
    label: "att name 006"
    input: string
    description: "Name"
  att name 007:
    label: "att name 007"
    input: string
    description: "Name"
  att name 008:
    label: "att name 008"
    input: string
    description: "Name"
  att name 009:
    label: "att name 009"
    input: string
    description: "Name"
  att name 010:
    label: "att name 010"
    input: string
    description: "Name"
  att score 001:
    label: "att score 001"
    input: string
    description: "Score"
  att score 002:
    label: "att score 002"
    input: string
    description: "Score"
  att score 003:
    label: "att score 003"
    input: string
    description: "Score"
  att score 004:
    label: "att score 004"
    input: string
    description: "Score"
  att score 005:
    label: "att score 005"
    input: string
    description: "Score"
  att score 006:
    label: "att score 006"
    input: string
    description: "Score"
  att score 007:
    label: "att score 007"
    input: string
    description: "Score"
  att score 008:
    label: "att score 008"
    input: string
    description: "Score"
  att score 009:
    label: "att score 009"
    input: string
    description: "Score"
  att score 010:
    label: "att score 010"
    input: string
    description: "Score"
  att die 001:
    label: "att die 001"
    input: string
    description: "Die"
  att die 002:
    label: "att die 002"
    input: string
    description: "Die"
  att die 003:
    label: "att die 003"
    input: string
    description: "Die"
  att die 004:
    label: "att die 004"
    input: string
    description: "Die"
  att die 005:
    label: "att die 005"
    input: string
    description: "Die"
  att die 006:
    label: "att die 006"
    input: string
    description: "Die"
  att die 007:
    label: "att die 007"
    input: string
    description: "Die"
  att die 008:
    label: "att die 008"
    input: string
    description: "Die"
  att die 009:
    label: "att die 009"
    input: string
    description: "Die"
  att die 010:
    label: "att die 010"
    input: string
    description: "Die"
  att type 001:
    label: "att type 001"
    input: string
    description: "Type"
  att type 002:
    label: "att type 002"
    input: string
    description: "Type"
  att type 003:
    label: "att type 003"
    input: string
    description: "Type"
  att type 004:
    label: "att type 004"
    input: string
    description: "Type"
  att type 005:
    label: "att type 005"
    input: string
    description: "Type"
  att type 006:
    label: "att type 006"
    input: string
    description: "Type"
  att type 007:
    label: "att type 007"
    input: string
    description: "Type"
  att type 008:
    label: "att type 008"
    input: string
    description: "Type"
  att type 009:
    label: "att type 009"
    input: string
    description: "Type"
  att type 010:
    label: "att type 010"
    input: string
    description: "Type"
  att range 001:
    label: "att range 001"
    input: string
    description: "Range"
  att range 002:
    label: "att range 002"
    input: string
    description: "Range"
  att range 003:
    label: "att range 003"
    input: string
    description: "Range"
  att range 004:
    label: "att range 004"
    input: string
    description: "Range"
  att range 005:
    label: "att range 005"
    input: string
    description: "Range"
  att range 006:
    label: "att range 006"
    input: string
    description: "Range"
  att range 007:
    label: "att range 007"
    input: string
    description: "Range"
  att range 008:
    label: "att range 008"
    input: string
    description: "Range"
  att range 009:
    label: "att range 009"
    input: string
    description: "Range"
  att range 010:
    label: "att range 010"
    input: string
    description: "Range"
  att damage 001:
    label: "att damage 001"
    input: string
    description: "Damage"
  att damage 002:
    label: "att damage 002"
    input: string
    description: "Damage"
  att damage 003:
    label: "att damage 003"
    input: string
    description: "Damage"
  att damage 004:
    label: "att damage 004"
    input: string
    description: "Damage"
  att damage 005:
    label: "att damage 005"
    input: string
    description: "Damage"
  att damage 006:
    label: "att damage 006"
    input: string
    description: "Damage"
  att damage 007:
    label: "att damage 007"
    input: string
    description: "Damage"
  att damage 008:
    label: "att damage 008"
    input: string
    description: "Damage"
  att damage 009:
    label: "att damage 009"
    input: string
    description: "Damage"
  att damage 010:
    label: "att damage 010"
    input: string
    description: "Damage"
  skill points spent:
    label: "skill points spent"
    input: string
    description: "Skill Points Spent"
  skill points stored:
    label: "skill points stored"
    input: string
    description: "Skill Points Stored"
  hero level:
    label: "hero level"
    input: string
    description: "Hero Level"
  contacts:
    label: "contacts"
    input: string
    description: ""
  enemies:
    label: "enemies"
    input: string
    description: ""
  equipment:
    label: "equipment"
    input: text
    description: ""
    rows: 3
  notes:
    label: "notes"
    input: text
    description: ""
    rows: 3
