fields:
### include: include/header.twig
### include: include/data.twig
# sheet: eote
  # row
    # col: col-12 col-md-6 c
  text:
    label: "todo: skills, css, collapsible sections, overflow scrollers, auto-hide logo + portrait"
      # br
  image:
    label: "Star Wars: Edge of the Empire"
    url: /uploads/images/dad560ee423b9f8c838d57a1d1ed42ad.webp
    width: 250px
      # br
      # card: personal: Personal Data
        # card-body
          # table
            # width: 30%
  name:
    label: "Character"
    input: string
    required: true
    placeholder: "Name of the Hero"
  species:
    label: "Species"
    input: string
  career:
    label: "Career"
    input: string
  spec trees:
    label: "Specialization Trees"
    input: string
  xp unspent:
    label: "Available XP"
    input: string
  xp total:
    label: "Total XP"
    input: string
  gender:
    label: "Gender"
    input: string
  age:
    label: "Age"
    input: string
  height:
    label: "Height"
    input: string
  build:
    label: "Build"
    input: string
  hair:
    label: "Hair"
    input: string
  eyes:
    label: "Eyes"
    input: string
  notable features:
    label: "Notable Features"
    input: text
    rows: 3
  player:
    label: "Player"
    input: string
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
  # br
  # br
  portrait:
    label: "Portrait"
    input: integer
    render: image
    # /col
  # /row
  # row
    # col: col-12 col-sm-6 col-md-3 col-lg-3
      # card: misc soak: Soak Value
        # card-body
  soak t:
    input: string
        # /card-body
      # /card
    # /col
    # col: col-12 col-sm-6 col-md-3 col-lg-3
      # card: misc wounds: Wounds
        # card-body
  wounds t:
    label: "Threshold"
    input: string
  wounds c:
    label: "Current"
    input: string
        # /card-body
      # /card
    # /col
    # col: col-12 col-sm-6 col-md-3 col-lg-3
      # card: misc strain: Strain
        # card-body
  strain t:
    label: "Threshold"
    input: string
  strain c:
    label: "Current"
    input: string
        # /card-body
      # /card
    # /col
    # col: col-12 col-sm-6 col-md-3 col-lg-3
      # card: misc defense: Defense
        # card-body
  defense r:
    label: "Ranged"
    input: string
  defense m:
    label: "Melee"
    input: string
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 c
      # card: characteristics: Characteristics
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-4 col-lg-2
      # card: attributes brawn
        # card-body
  brawn:
    label: "Brawn"
    input: string
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4 col-lg-2
      # card: attributes agility
        # card-body
  agility:
    label: "Agility"
    input: string
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4 col-lg-2
      # card: attributes vitality
        # card-body
  intellect:
    label: "Intellect"
    input: string
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4 col-lg-2
      # card: attributes cunning
        # card-body
  cunning:
    label: "Cunning"
    input: string
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4 col-lg-2
      # card: attributes agility
        # card-body
  willpower:
    label: "Willpower"
    input: string
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4 col-lg-2
      # card: attributes vitality
        # card-body
  presence:
    label: "Presence"
    input: string
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 c
      # card: skills: Skills
        # table: horiz
          # iter: 40
  skill name:
    label: "Skill"
    input: string
  skill attr:
    label: "Attribute"
    input: string
  skill career:
    label: "Career"
    input: string
  skill rank:
    label: "Rank"
    input: integer
    min: 0
    max: 5
          # /iter
        # /table
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: weapons: Weapons
        # card-body
          # table: horiz
            # iter: 8
              # width: 140px
  weapon name:
    label: "Weapon"
    input: string
    description: "Weapon Name"
              # width: 150px
  weapon skill:
    label: "Skill"
    input: select
    description: "Weapon Skill"
    options:
      "Ranged (Light)": "Ranged (Light)"
      "Ranged (Heavy)": "Ranged (Heavy)"
      "Gunnery": "Gunnery"
      "Brawl": "Brawl"
      "Melee": "Melee"
      "Lightsaber": "Lightsaber"
              # width: 40px
  weapon damage:
    label: "Damage"
    input: string
              # width: 90px
  weapon range:
    label: "Range"
    input: string
              # width: 40px
  weapon crit:
    label: "Crit"
    input: string
  weapon special:
    label: "Special"
    input: string
            # /iter
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-6
      # card: motivations: Motivations
        # card-body:
          # row
            # col: col-12 col-md-6
  motiv type 1:
    label: "Type"
    input: string
  motiv desc 1:
    input: text
    rows: 3
            # /col
            # col: col-12 col-md-6
  motiv type 2:
    label: "Type"
    input: string
  motiv desc 2:
    input: text
    rows: 3
            # /col
          # /row
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: obligations: Obligations
        # card-body:
          # row
            # col: col-12 col-md-6
  oblig type 1:
    label: "Type"
    input: string
  oblig magni 1:
    label: "Magnitude"
    input: string
            # /col
            # col: col-12 col-md-6
  oblig type 2:
    label: "Type"
    input: string
  oblig magni 2:
    label: "Magnitude"
    input: string
            # /col
            # col: col-12
  group contrib:
    label: "Group's Contribution Rank"
    input: string
            # /col
          # /row
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: equipment: Equipment Log
        # card-body:
          # row
            # col: col-12
  credits:
    label: "Credits"
    input: string
            # /col
          # col: col-12 col-md-6
  equip armor:
    label: "Equipment &amp; Armor"
    input: text
    rows: 3
            # /col
            # col: col-12 col-md-6
  personal gear:
    label: "Personal Gear"
    input: text
    rows: 3
            # /col
          # /row
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: inuries: Critical Injuries
        # card-body:
          # table: horiz
            # iter: 6
  injury severity:
    label: "Severity"
    input: string
  injury result:
    label: "Result"
    input: string
            # /iter
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: talents: Talents and Special Abilities
        # card-body:
          # table: horiz
            # iter: 14
              # width: 25%
  talent name:
    label: "Name"
    input: string
              # width: 50
  talent page:
    label: "Page #"
    input: string
  talent summary:
    label: "Summary"
    input: string
            # /iter
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: notes: Character Notes
        # card-body: mention
  notes:
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
  # /row
  # include: include/footer.twig
# /sheet