fields:
# include: header.twig
# include: data.twig
# sheet: Basic Roleplaying
  # row
    # col: col-12 col-md-6
      # card: personal: Personal
        # card-body
          # table
  name:
    label: "Name"
    input: string
    placeholder: "Name of the hero"
    required: true
  culture:
    label: "Culture"
    input: string
    placeholder: ""
  gender:
    label: "Gender"
    input: string
  handedness:
    label: "Handedness"
    input: select
    options:
      right: right
      left: left
      ambidextrous: ambidextrous
  height:
    label: "Height"
    input: string
  weight:
    label: "Weight"
    input: string
  profession:
    label: "Profession"
    input: string
    placeholder: ""
  wealth:
    label: "Wealth"
    input: string
    placeholder: ""
  gods religion:
    label: "Gods / Religion"
    input: string
    placeholder: ""
  distinctive features:
    label: "Distinctive Features"
    input: string
    placeholder: ""
  move:
    label: "Movement (MOV)"
    input: string
  description:
    label: "Description"
    input: text
    rows: 3
  age:
    label: "Age"
    input: string
  portrait:
    label: "Portrait"
    input: integer
    render: image
    placeholder: "WA image ID"
  player:
    label: "Player"
    input: string
    placeholder: "Your name"
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: characteristics: Characteristics
        # card-body
          # table
  str:
    label: "STR"
    input: string
    placeholder: "Strength"
    description: "for Effort Roll"
    required: true
  con:
    label: "CON"
    input: string
    placeholder: "Constitution"
    description: "for Stamina Roll"
    required: true
  siz:
    label: "SIZ"
    input: string
    placeholder: "Size"
    description: "for Damage Modifier"
    required: true
  int:
    label: "INT"
    input: string
    placeholder: "Intelligence"
    description: "for Idea Roll"
    required: true
  pow:
    label: "POW"
    input: string
    placeholder: "Power"
    description: "for Luck Roll"
    required: true
  dex:
    label: "DEX"
    input: string
    placeholder: "Dexterity"
    description: "for Agility Roll"
    required: true
  cha:
    label: "CHA"
    input: string
    placeholder: "Charisma"
    description: "for Charm Roll"
    required: true
  edu:
    label: "EDU"
    input: string
    placeholder: "Education"
    description: "for Knowledge Roll"
    required: true
  pow mark:
    input: checkbox
    placeholder: ""
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: hit points: Hit Points
        # card-body
          # table: horiz
  major wound:
    label: "Major Wound"
    input: string
  dead:
    label: "Dead"
    input: string
  hit points current:
    label: "Hit Points Current"
    input: string
  hit points max:
    label: "Hit Points Max"
    input: string
  hit points notes:
    label: "Hit Points Notes"
    input: string
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: skills: Skills
        # card-body
          # row
            # col: col-12 col-md-4
              # table: horiz
                # iter
  skill name:
    label: "Name"
    input: string
    placeholder: ""
  skill value:
    label: "%"
    input: string
    placeholder: ""
  skill mark:
    input: checkbox
    placeholder: ""
                # /iter
              # /table
            # /col
            # col: col-12 col-md-4
              # table: horiz
                # iter
  skill name:
    label: "Name"
    input: string
    placeholder: ""
  skill value:
    label: "%"
    input: string
    placeholder: ""
  skill mark:
    input: checkbox
    placeholder: ""
                # /iter
              # /table
            # /col
            # col: col-12 col-md-4
              # table: horiz
                # iter
  skill name:
    label: "Name"
    input: string
    placeholder: ""
  skill value:
    label: "%"
    input: string
    placeholder: ""
  skill mark:
    input: checkbox
    placeholder: ""
                # /iter
              # /table
            # /col
         # /row
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: weapons: Weapons
        # card-body
          # table: horiz
            # iter
  weapon type:
    label: "Type"
    input: string
    placeholder: ""
  weapon value:
    label: "%"
    input: string
    placeholder: ""
  weapon damage:
    label: "Damage"
    input: string
    placeholder: ""
  weapon range:
    label: "Range"
    input: string
    placeholder: ""
  weapon attacks:
    label: "Attacks"
    input: string
    placeholder: ""
  weapon length:
    label: "Length"
    input: string
    placeholder: ""
  weapon hand:
    label: "Hand"
    input: string
    placeholder: ""
  weapon hp:
    label: "HP"
    input: string
    placeholder: ""
  weapon mark:
    input: checkbox
    placeholder: "Marked"
            # /iter
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: armor: Armor
        # card-body
          # table: horiz
            # iter
  armor type:
    label: "Type"
    input: string
    placeholder: ""
  armor value:
    label: "%"
    input: string
    placeholder: ""
  shield type:
    label: "Shield Type"
    input: string
    placeholder: ""
  shiele value:
    label: "%"
    input: string
    placeholder: ""
  shield damage:
    label: "Damage"
    input: string
    placeholder: ""
  shield hp:
    label: "HP"
    input: string
    placeholder: ""
  shield mark:
    input: checkbox
    placeholder: "Marked"
  combat notes:
    label: "Notes"
    input: text
    rows: 3
    placeholder: ""
            # /iter
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: character points: Character Points
        # card-body
          # table: horiz
  campaign power level:
    label: "Campaign Power Level"
    input: string
    placeholder: ""
  character points:
    label: "Character Points"
    input: string
    placeholder: ""
          # /table
          # table: horiz
            # iter: 6
  character failing type:
    label: "Character Failings"
    input: string
    placeholder: ""
  character failing points:
    label: "Points"
    input: string
    placeholder: ""
            # /iter
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: power points: Power Points
        # card-body
          # table: horiz
  power points current:
    label: "Current"
    input: string
    placeholder: ""
  power points max:
    label: "Max"
    input: string
    placeholder: ""
  battery:
    label: "Battery"
    input: string
    placeholder: ""
          # /table
        # /card-body
      # /card
      # card: fatigue points: Fatigue Points
        # card-body
          # table: horiz
  fatigue points current:
    label: "Current"
    input: string
    placeholder: ""
  fatigue points max:
    label: "Max"
    input: string
    placeholder: ""
  fatigue notes:
    label: "Notes"
    input: string
    placeholder: ""
          # /table
        # /card-body
      # /card
      # card: sanity points: Sanity Points
        # card-body
          # table: horiz
  sanity points current:
    label: "Current"
    input: string
    placeholder: ""
  sanity points max:
    label: "Max"
    input: string
    placeholder: ""
  sanity points temporary:
    label: "Temporary"
    input: string
    placeholder: ""
  sanity points notes:
    label: "Notes"
    input: string
    placeholder: ""
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: powers: Powers
        # card-body
          # table: horiz
            # iter: 8
  power name:
    label: "Power"
    input: string
    placeholder: ""
  power type:
    label: "Energy Type"
    input: string
    placeholder: ""
  power levels act:
    label: "Active Levels"
    input: string
    placeholder: ""
  power levels total:
    label: "Total Levels"
    input: string
    placeholder: ""
  power range:
    label: "Range"
    input: string
    placeholder: ""
  power cost:
    label: "Cost To Use"
    input: string
    placeholder: ""
  power duration:
    label: "Duration"
    input: string
    placeholder: ""
  power notes:
    label: "Notes"
    input: string
    placeholder: ""
  power cp:
    label: "CP"
    input: string
    placeholder: ""
            # /iter
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: attack powers: Attack Powers
        # card-body
          # table: horiz
            # iter: 6
  apower name:
    label: "Name"
    input: string
    placeholder: ""
  apower value:
    label: "%"
    input: string
    placeholder: ""
  apower damage:
    label: "Damage"
    input: string
    placeholder: ""
  apower range:
    label: "Range"
    input: string
    placeholder: ""
  apower type:
    label: "Type"
    input: string
    placeholder: ""
  apower cost:
    label: "Cost"
    input: string
    placeholder: ""
  apower mark:
    input: checkbox
    placeholder: ""
            # /iter
          # /table
          # table
  apower projection:
    label: "Projection"
    input: string
    placeholder: ""
  apower throw:
    label: "Throw"
    input: string
    placeholder: ""
  apower brawl:
    label: "Brawl"
    input: string
    placeholder: ""
  apower fly:
    label: "Fly"
    input: string
    placeholder: ""
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: defensive powers: Defensive Powers
        # card-body
          # table: horiz
            # iter: 6
  dpower name:
    label: "Power"
    input: string
    placeholder: ""
  dpower type:
    label: "Energy Type"
    input: string
    placeholder: ""
  dpower level:
    label: "Level"
    input: string
    placeholder: ""
  dpower value:
    label: "%"
    input: string
    placeholder: ""
  dpower cost:
    label: "Energy Cost"
    input: string
    placeholder: ""
            # /iter
          # /table
          # table
  dpower defense:
    label: "Defense"
    input: string
    placeholder: ""
  dpower dodge:
    label: "Dodge"
    input: string
    placeholder: ""
  dpower dodge mark:
    input: checkbox
    placeholder: ""
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: notes: Notes
        # card-body
  notes:
    label: "notes"
    input: text
    rows: 3
    placeholder: ""
        # /card-body
      # /card
    # /col
  # /row
# /sheet
# include: footer.twig
