fields:
  gender:
    label: "Gender"
    input: string
  age:
    label: "Age"
    input: integer
  origin:
    label: "Origin"
    input: string
    placeholder: "eg Earther, Martian, Belter"
  background:
    label: "Background"
    input: string
    placeholder: "eg Academic"
  social class:
    label: "Social Class"
    input: string
    placeholder: "eg middle"
  profession:
    label: "profession"
    input: string
    placeholder: "eg Expert"
  drive:
    label: "Drive"
    input: text
    rows: 3
    placeholder: ""
  appearance:
    label: "Appearance"
    input: text
    rows: 3
    placeholder: ""
  accuracy:
    label: "Accuracy"
    description: "Accuracy measures aim and precision, and measures your ability to hit targets with ranged or thrown weapons."
    placeholder: "-2 (quite poor) to 4 (truly outstanding), average is 0, default for players is 1" 
    input: integer
  accuracy_focus:
    label: "Accuracy Focus"
    input: text
    rows: 5
    description: "Bows, Gunnery, Pistols, Rifles, Throwing"
  communication:
    label: "Communication"
    description: "Communication covers social skills and generally making friends and influencing people."
    placeholder: "-2 (quite poor) to 4 (truly outstanding), average is 0, default for players is 1" 
    input: integer
  communication_focus:
    label: "Communication Focus"
    description: "Bargaining, Deception, Disguise, Etiquette, Expression, Gambling, Investigation, Leadership, Performing, Persuasion, Seduction"
    input: text
    rows: 5
  constitution:
    label: "Constitution"
    description: "Constitution is your character’s overall health, fortitude, and resistance to harm, illness, and fatigue."
    placeholder: "-2 (quite poor) to 4 (truly outstanding), average is 0, default for players is 1" 
    input: integer
  constitution_focus:
    label: "Constitution Focus"
    description: "Running, Stamina, Swimming, Tolerance"
    input: text
    rows: 5
  dexterity:
    label: "Dexterity"
    description: "Dexterity covers deftness, agility, and reaction time, affecting how quickly and gracefully you move."
    placeholder: "-2 (quite poor) to 4 (truly outstanding), average is 0, default for players is 1" 
    input: integer
  dexterity_focus:
    label: "Dexterity Focus"
    description: "Acrobatics, Crafting, Driving, Initiative, Piloting, Sleight of Hand, Stealth"
    input: text
    rows: 5
  fighting:
    label: "Fighting"
    description: "Fighting is your character’s capability in close combat, ranging from a brawl to wielding weapons."
    placeholder: "-2 (quite poor) to 4 (truly outstanding), average is 0, default for players is 1" 
    input: integer
  fighting_focus:
    label: "Fighting Focus"
    description: "Brawling, Grappling, Heavy Weapons, Light Weapons"
    input: text
    rows: 5
  intelligence:
    label: "Intelligence"
    description: "Intelligence measures a character’s reasoning, memory, problem-solving, and overall knowledge."
    placeholder: "-2 (quite poor) to 4 (truly outstanding), average is 0, default for players is 1" 
    input: integer
  intelligence_focus:
    label: "Intelligence Focus"
    description: "Art, Business, Cryptography, Current Affairs, Demolitions, Engineering, Evaluation, History, Law, Medicine, Navigation, Research, Science, Security, Tactics, Technology"
    input: text
    rows: 5
  perception:
    label: "Perception"
    description: "Perception is the ability to pick up on and notice things using any of the character’s senses."
    placeholder: "-2 (quite poor) to 4 (truly outstanding), average is 0, default for players is 1" 
    input: integer
  perception_focus:
    label: "Perception Focus"
    description: "Empathy, Hearing, Intuition, Searching, Seeing, Smelling, Survival, Tasting, Touching, Tracking"
    input: text
    rows: 5
  strength:
    label: "Strength"
    description: "Strength is sheer muscle power and the ability to apply it, from lifting heavy things to feats of athletics."
    placeholder: "-2 (quite poor) to 4 (truly outstanding), average is 0, default for players is 1" 
    input: integer
  strength_focus:
    label: "Strength Focus"
    description: "Climbing, Intimidation, Jumping, Might"
    input: text
    rows: 5
  willpower:
    label: "Willpower"
    description: "Willpower measures self-control, self-discipline, mental fortitude, and confidence."
    placeholder: "-2 (quite poor) to 4 (truly outstanding), average is 0, default for players is 1" 
    input: integer
  willpower_focus:
    label: "Willpower Focus"
    description: "Courage, Faith, Self-Discipline"
    input: text
    rows: 5
  talents and specializations:
    label: "Talents and Specializations"
    input: text
    rows: 10
  relationships:
    label: "Relationships"
    input: text
    rows: 20
  goals:
    label: "Goals"
    input: text
    rows: 20
  prefered stunts:
    label: "Preferred Stunts"
    input: text
    rows: 20
  income:
    label: "Income"
    input: integer
  money:
    label: "Money"
    input: integer
    description: "The money you possess."
  equipment:
    label: "Equipment"
    input: text
    rows: 20
  experience:
    label: "Experience"
    input: integer
  level:
    label: "Level"
    input: integer
  fortune:
    label: "Fortune"
    input: integer
    description: "Starts at 15 plus anything you got from Drive."
  defense:
    label: "Defense"
    input: integer
    description: "Starts at 10 + DEX."
  toughness:
    label: "Toughness"
    input: integer
    description: "Toughness equals your CON, minimum is 0."
  armor type:
    label: "Armor Type"
    input: string
    placeholder: "eg Medium Armor and Riot Shield"
  armor bonus:
    label: "Armor Bonus"
    input: integer
    placeholder: "eg +4"
  armor penalty:
    label: "Armor Penalty"
    input: integer
    placeholder: "eg -2"
  con_blinded:
    label: "Condition Blinded"
    input: checkbox
  con_deafened:
    label: "Condition Deafened"
    input: checkbox
  con_dying:
    label: "Condition Dying"
    input: checkbox
  con_exhausted:
    label: "Condition Exhausted"
    input: checkbox
  con_fatigued:
    label: "Condition Fatigued"
    input: checkbox
  con_free_falling:
    label: "Condition Free-Falling"
    input: checkbox
  con_helpless:
    label: "Condition Helpless"
    input: checkbox
  con_hindered:
    label: "Condition Hindered"
    input: checkbox
  con_injured:
    label: "Condition Injured"
    input: checkbox
  con_prone:
    label: "Condition Prone"
    input: checkbox
  con_restrained:
    label: "Condition Restrained"
    input: checkbox
  con_unconscious:
    label: "Condition Unconscious"
    input: checkbox
  con_wounded:
    label: "Condition Wounded"
    input: checkbox
  notes:
    label: "Notes"
    input: text
    rows: 20
  memberships:
    label: "Memberships"
    input: text
    rows: 20
  reputation:
    label: "Reputation"
    input: text
    rows: 20
  weapon name 01:
    label: "Weapon Name 01"
    input: string
  weapon attack ability 01:
    label: "Weapon Attack Ability 01"
    input: select
    options:
      NONE: NONE
      DEX: DEX
      PER: PER
      STR: STR
  weapon damage 01:
    label: "Weapon Damage 01"
    input: string
  weapon qualities 01:
    label: "Weapon Qualities 01"
    input: text
    rows: 3
  weapon name 02:
    label: "Weapon Name 02"
    input: string
  weapon attack ability 02:
    label: "Weapon Attack Ability 02"
    input: select
    options:
      NONE: NONE
      DEX: DEX
      PER: PER
      STR: STR
  weapon damage 02:
    label: "Weapon Damage 02"
    input: string
  weapon qualities 02:
    label: "Weapon Qualities 02"
    input: text
    rows: 3
  weapon name 03:
    label: "Weapon Name 03"
    input: string
  weapon attack ability 03:
    label: "Weapon Attack Ability 03"
    input: select
    options:
      NONE: NONE
      DEX: DEX
      PER: PER
      STR: STR
  weapon damage 03:
    label: "Weapon Damage 03"
    input: string
  weapon qualities 03:
    label: "Weapon Qualities 03"
    input: text
    rows: 3
  weapon name 04:
    label: "Weapon Name 04"
    input: string
  weapon attack ability 04:
    label: "Weapon Attack Ability 04"
    input: select
    options:
      NONE: NONE
      DEX: DEX
      PER: PER
      STR: STR
  weapon damage 04:
    label: "Weapon Damage 04"
    input: string
  weapon qualities 04:
    label: "Weapon Qualities 04"
    input: text
    rows: 3
  weapon name 05:
    label: "Weapon Name 05"
    input: string
  weapon attack ability 05:
    label: "Weapon Attack Ability 05"
    input: select
    options:
      NONE: NONE
      DEX: DEX
      PER: PER
      STR: STR
  weapon damage 05:
    label: "Weapon Damage 05"
    input: string
  weapon qualities 05:
    label: "Weapon Qualities 05"
    input: text
    rows: 3
  weapon name 06:
    label: "Weapon Name 06"
    input: string
  weapon attack ability 06:
    label: "Weapon Attack Ability 06"
    input: select
    options:
      NONE: NONE
      DEX: DEX
      PER: PER
      STR: STR
  weapon damage 06:
    label: "Weapon Damage 06"
    input: string
  weapon qualities 06:
    label: "Weapon Qualities 06"
    input: text
    rows: 3
  weapon name 07:
    label: "Weapon Name 07"
    input: string
  weapon attack ability 07:
    label: "Weapon Attack Ability 07"
    input: select
    options:
      NONE: NONE
      DEX: DEX
      PER: PER
      STR: STR
  weapon damage 07:
    label: "Weapon Damage 07"
    input: string
  weapon qualities 07:
    label: "Weapon Qualities 07"
    input: text
    rows: 3
  weapon name 08:
    label: "Weapon Name 08"
    input: string
  weapon attack ability 08:
    label: "Weapon Attack Ability 08"
    input: select
    options:
      NONE: NONE
      DEX: DEX
      PER: PER
      STR: STR
  weapon damage 08:
    label: "Weapon Damage 08"
    input: string
  weapon qualities 08:
    label: "Weapon Qualities 08"
    input: text
    rows: 3
  weapon name 09:
    label: "Weapon Name 09"
    input: string
  weapon attack ability 09:
    label: "Weapon Attack Ability 09"
    input: select
    options:
      NONE: NONE
      DEX: DEX
      PER: PER
      STR: STR
  weapon damage 09:
    label: "Weapon Damage 09"
    input: string
  weapon qualities 09:
    label: "Weapon Qualities 09"
    input: text
    rows: 3
  weapon name 10:
    label: "Weapon Name 10"
    input: string
  weapon attack ability 10:
    label: "Weapon Attack Ability 10"
    input: select
    options:
      NONE: NONE
      DEX: DEX
      PER: PER
      STR: STR
  weapon damage 10:
    label: "Weapon Damage 10"
    input: string
  weapon qualities 10:
    label: "Weapon Qualities 10"
    input: text
    rows: 3
  talent name 01:
    label: "Talent Name 01"
    input: string
  talent degree 01:
    label: "Talent Degree 01"
    input: select
    options:
      novice: novice
      expert: expert
      master: master
  talent effect 01:
    label: "Talent Effect 01"
    input: text
    rows: 3
  talent name 02:
    label: "Talent Name 02"
    input: string
  talent degree 02:
    label: "Talent Degree 02"
    input: select
    options:
      novice: novice
      expert: expert
      master: master
  talent effect 02:
    label: "Talent Effect 02"
    input: text
    rows: 3
  talent name 03:
    label: "Talent Name 03"
    input: string
  talent degree 03:
    label: "Talent Degree 03"
    input: select
    options:
      novice: novice
      expert: expert
      master: master
  talent effect 03:
    label: "Talent Effect 03"
    input: text
    rows: 3
  talent name 04:
    label: "Talent Name 04"
    input: string
  talent degree 04:
    label: "Talent Degree 04"
    input: select
    options:
      novice: novice
      expert: expert
      master: master
  talent effect 04:
    label: "Talent Effect 04"
    input: text
    rows: 3
  talent name 05:
    label: "Talent Name 05"
    input: string
  talent degree 05:
    label: "Talent Degree 05"
    input: select
    options:
      novice: novice
      expert: expert
      master: master
  talent effect 05:
    label: "Talent Effect 05"
    input: text
    rows: 3
  talent name 06:
    label: "Talent Name 06"
    input: string
  talent degree 06:
    label: "Talent Degree 06"
    input: select
    options:
      novice: novice
      expert: expert
      master: master
  talent effect 06:
    label: "Talent Effect 06"
    input: text
    rows: 3
  talent name 07:
    label: "Talent Name 07"
    input: string
  talent degree 07:
    label: "Talent Degree 07"
    input: select
    options:
      novice: novice
      expert: expert
      master: master
  talent effect 07:
    label: "Talent Effect 07"
    input: text
    rows: 3
  talent name 08:
    label: "Talent Name 08"
    input: string
  talent degree 08:
    label: "Talent Degree 08"
    input: select
    options:
      novice: novice
      expert: expert
      master: master
  talent effect 08:
    label: "Talent Effect 08"
    input: text
    rows: 3
  talent name 09:
    label: "Talent Name 09"
    input: string
  talent degree 09:
    label: "Talent Degree 09"
    input: select
    options:
      novice: novice
      expert: expert
      master: master
  talent effect 09:
    label: "Talent Effect 09"
    input: text
    rows: 3
  talent name 10:
    label: "Talent Name 10"
    input: string
  talent degree 10:
    label: "Talent Degree 10"
    input: select
    options:
      novice: novice
      expert: expert
      master: master
  talent effect 10:
    label: "Talent Effect 10"
    input: text
    rows: 3
  talent name 11:
    label: "Talent Name 11"
    input: string
  talent degree 11:
    label: "Talent Degree 11"
    input: select
    options:
      novice: novice
      expert: expert
      master: master
  talent effect 11:
    label: "Talent Effect 11"
    input: text
    rows: 3
  talent name 12:
    label: "Talent Name 12"
    input: string
  talent degree 12:
    label: "Talent Degree 12"
    input: select
    options:
      novice: novice
      expert: expert
      master: master
  talent effect 12:
    label: "Talent Effect 12"
    input: text
    rows: 3
  talent name 13:
    label: "Talent Name 13"
    input: string
  talent degree 13:
    label: "Talent Degree 13"
    input: select
    options:
      novice: novice
      expert: expert
      master: master
  talent effect 13:
    label: "Talent Effect 13"
    input: text
    rows: 3
  talent name 14:
    label: "Talent Name 14"
    input: string
  talent degree 14:
    label: "Talent Degree 14"
    input: select
    options:
      novice: novice
      expert: expert
      master: master
  talent effect 14:
    label: "Talent Effect 14"
    input: text
    rows: 3
  talent name 15:
    label: "Talent Name 15"
    input: string
  talent degree 15:
    label: "Talent Degree 15"
    input: select
    options:
      novice: novice
      expert: expert
      master: master
  talent effect 15:
    label: "Talent Effect 15"
    input: text
    rows: 3
  talent name 16:
    label: "Talent Name 16"
    input: string
  talent degree 16:
    label: "Talent Degree 16"
    input: select
    options:
      novice: novice
      expert: expert
      master: master
  talent effect 16:
    label: "Talent Effect 16"
    input: text
    rows: 3
  talent name 17:
    label: "Talent Name 17"
    input: string
  talent degree 17:
    label: "Talent Degree 17"
    input: select
    options:
      novice: novice
      expert: expert
      master: master
  talent effect 17:
    label: "Talent Effect 17"
    input: text
    rows: 3
  talent name 18:
    label: "Talent Name 18"
    input: string
  talent degree 18:
    label: "Talent Degree 18"
    input: select
    options:
      novice: novice
      expert: expert
      master: master
  talent effect 18:
    label: "Talent Effect 18"
    input: text
    rows: 3
  talent name 19:
    label: "Talent Name 19"
    input: string
  talent degree 19:
    label: "Talent Degree 19"
    input: select
    options:
      novice: novice
      expert: expert
      master: master
  talent effect 19:
    label: "Talent Effect 19"
    input: text
    rows: 3
  talent name 20:
    label: "Talent Name 20"
    input: string
  talent degree 20:
    label: "Talent Degree 20"
    input: select
    options:
      novice: novice
      expert: expert
      master: master
  talent effect 20:
    label: "Talent Effect 20"
    input: text
    rows: 3
  col_ships_vehicles:
    label: "col ships vehicles"
    input: text
    rows: 2
    placeholder: "put the blockids of your ships or vehicles here, eg 16526, 2354, 11234"
