# sheet: Umbra RPG Character
fields:
  # row
    # col: col-12 col-md-8
      # card: personal: Personal Information
        # card-body
          # table
  name:
    label: "name"
    input: string
    placeholder: "Name of the hero"
    description: "This is the name of your hero."
    required: true
  size:
    label: "size"
    input: string
  upbringing:
    label: "upbringing"
    input: string
  destiny:
    label: "destiny"
    input: string
  ancestry:
    label: "ancestry"
    input: string
  reputation:
    label: "reputation"
    input: string
  player:
    label: "player"
    input: string
  xp gained:
    label: "xp gained"
    input: integer
  xp used:
    label: "xp used"
    input: integer
          # /table
        # /card-body
      # /card
    # /col
    # col: col-4 col-lg-4 hidden-xs hidden-sm hidden-md d-none d-lg-block
      # card: portrait: Portrait
        # card-body
  portrait:
    label: "portrait"
    input: integer
    render: image
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # row
        # col: col-12 col-md-4
          # card: physical: Physical
            # card-body
              # table
  # dots: 6
  brawn:
    label: "brawn"
    input: string
  # dots: 6
  agility:
    label: "agility"
    input: string
  # dots: 6
  vitality:
    label: "vitality"
    input: string
              # /table
            # /card-body
          # /card
        # /col
        # col: col-12 col-md-4
          # card: mental: Mental
            # card-body
              # table
  # dots: 6
  intelligent:
    label: "intelligent"
    input: string
  # dots: 6
  wit:
    label: "wit"
    input: string
  # dots: 6
  charisma:
    label: "charisma"
    input: string
              # /table
            # /card-body
          # /card
        # /col
        # col: col-12 col-md-4
          # card: spiritual: Spiritual
            # card-body
              # table
  # dots: 6
  essence:
    label: "essence"
    input: string
  # dots: 6
  willpower:
    label: "willpower"
    input: string
  # dots: 6
  luck:
    label: "luck"
    input: string
              # /table
            # /card-body
          # /card
        # /col
      # /row
    # /col
  # /row
  # row
    # col: col-12 col-md-4
      # card: health: Health
        # card-body
          # table
  health present:
    label: "health present"
    input: integer
  health total:
    label: "health total"
    input: integer
  # dots: 14
  ### calculated: agility+brawn
  defence:
    label: "defence"
    input: integer
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4
      # card: other: Other
        # card-body
          # row
            # col: col-6
              # card: initiative
                # card-body
  initiative:
    label: "initiative"
    input: string
                # /card-body
              # /card
            # /col
            # col: col-6
              # card: speed
                # card-body
  speed:
    label: "speed"
    input: string
                # /card-body
              # /card
            # /col
          # /row
          # row
            # col: col-6
              # card: armour
                # card-body
  armour:
    label: "armour"
    input: string
                # /card-body
              # /card
            # /col
            # col: col-6
              # card: sight
                # card-body
  sight:
    label: "sight"
    input: string
                # /card-body
              # /card
            # /col
          # /row
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4
      # card: languages: Languages
        # card-body
  languages:
    label: "languages"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-6
      # card: skills: Skills
        # card-body
          # table: horiz
            # iter: 22
  skill name:
    label: "skill name"
    input: string
  skill attr:
    label: "skill attr"
    input: select
    options:
      brawn: brawn
      agility: agility
      intelligent: intelligent
      wit: wit
      charisma: charisma
      essence: essence
      willpower: willpower
  # dots: 4
  skill rank:
    label: "skill rank"
    input: string
            # /iter
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: weapons-and-armour: Weapons and Armor
        # card-body
          # table: horiz
            # iter: 12
  weap n arm name:
    label: "weap n arm name"
    input: string
  # dots: 4
  weap n arm rank:
    label: "weap n arm rank"
    input: string
            # /iter
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-8
      # card: weapons: Weapons
        # card-body
          # table: horiz
            # iter: 4
  weapon name:
    label: "weapon name"
    input: string
  weapon att:
    label: "weapon att"
    input: string
  weapon man1:
    label: "weapon man1"
    input: string
  weapon man2:
    label: "weapon man2"
    input: string
  weapon man3:
    label: "weapon man3"
    input: string
  weapon man4:
    label: "weapon man4"
    input: string
  weapon man5:
    label: "weapon man5"
    input: string
  weapon traits:
    label: "weapon traits"
    input: string
  weapon dmg:
    label: "weapon dmg"
    input: string
            # /iter
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4
      # card: weapons: Weapons
        # card-body
  spheres of magic:
    label: "spheres of magic"
    input: text
    rows: 3
          # table: horiz
  mana:
    label: "mana"
    input: string
  regen:
    label: "regen"
    input: string
          # /table
  magic one:
    label: "magic one"
    input: select
    options:
      intelligent: intelligent
      wit: wit
      charisma: charisma
  magic two:
    label: "magic two"
    input: select
    options:
      essence: essence
      willpower: willpower
  # dots: 20
  magic:
    label: "magic"
    input: integer
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: spells: Spells
        # card-body
  spellbook:
    label: "spellbook"
    input: string
          # table: horiz
            # iter: 21
  spell name:
    label: "spell name"
    input: string
  spell sphere:
    label: "spell sphere"
    input: string
  spell range:
    label: "spell range"
    input: string
  spell aoe targets:
    label: "spell aoe targets"
    input: string
  spell duration:
    label: "spell duration"
    input: string
  spell cost:
    label: "spell cost"
    input: string
  spell effects:
    label: "spell effects"
    input: text
    rows: 3
            # /iter
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-6
      # card: edges: Edges
        # card-body
  edges:
    label: "edges"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: flaws: Flaws
        # card-body
  flaws:
    label: "flaws"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: equipment: Equipment
        # card-body
  equipment:
    label: "equipment"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: notes: Notes
        # card-body: mention
  money:
    label: "money"
    input: string
  notes:
    label: "notes"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
  # /row
# /sheet