fields:
# include: include/header.twig
# sheet: Basic Roleplaying Monster light
  # row
    # col: col-12 col-md-8
      # card: basics
        # card-body
  name:
    label: "Name"
    input: string
    placeholder: "Name of the monster"
    required: true
  portrait:
    label: "Portrait"
    input: integer
    render: image
    placeholder: "WA image ID"
  description:
    label: "Description"
    input: text
    rows: 3
        # /card-body
      # /card
      # card: attributes
        # card-body
          # table:horiz
  str dice:
    label: "STR"
    input: string
    placeholder: "3d6"
    description: "Strength"
  con dice:
    label: "CON"
    input: string
    placeholder: "3d6"
    description: "Constitution"
  siz dice:
    label: "SIZ"
    input: string
    placeholder: "2d6+6"
    description: "Size"
  int dice:
    label: "INT"
    input: string
    placeholder: "2d6+6"
    description: "Intelligence"
  pow dice:
    label: "POW"
    input: string
    placeholder: "3d6"
    description: "Power"
  dex dice:
    label: "DEX"
    input: string
    placeholder: "3d6"
    description: "Dexterity"
  cha dice:
    label: "CHA"
    input: string
    placeholder: "3d6"
    description: "Charisma"
          # /table
          # table:horiz
  str:
    input: string
    placeholder: "3d6"
  con:
    input: string
    placeholder: "3d6"
  siz:
    input: string
    placeholder: "2d6+6"
  int:
    input: string
    placeholder: "2d6+6"
  pow:
    input: string
    placeholder: "3d6"
  dex:
    input: string
    placeholder: "3d6"
  cha:
    input: string
    placeholder: "3d6"
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # table: horiz
        # width: 50%
  move:
    label: "Move"
    input: integer
        # width: 50%
  hit points:
    label: "Hit Points"
    input: integer
      # /table
    # /col
    # col: col-12 col-md-6
      # table: horiz
        # width: 50%
  damage modifier:
    label: "Damage Modifier"
    input: string
        # width: 50%
  armor:
    label: "Armor"
    input: string
      # /table
    # /col
    # col: col-12
      # card: attacks
        # card-body
  attacks:
    label: "Attacks"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
    # col: col-12
      # card: skills
        # card-body
  Skills:
    label: "Skills"
    input: text
    placeholder: "eg Appraise 35%, Bargain 35%, Craft (farming) 75%, ..."
    rows: 3
        # /card-body
      # /card
    # /col
    # col: col-12
      # card: powers
        # card-body
  powers:
    label: "Powers"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
    # col: col-12
      # card: powers
        # card-body
  belongings:
    label: "Belongings"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
  # /row
# include: include/footer.twig
# /sheet