fields:
  species:
    required: true
    label: "Species"
    description: "Your character's species"
    input: string
    placeholder: "eg human"
  environment:
    label: "Environment"
    description: ""
    input: string
  assignment:
    label: "Assignment"
    description: ""
    input: string
  rank:
    label: "Rank"
    description: ""
    input: string
  upbringing:
    label: "Upbringing"
    description: ""
    input: string
  traits:
    label: "Traits"
    description: ""
    input: string
  values:
    label: "Values"
    description: "Notes"
    input: text
    rows: 10
  att control:
    label: "Control"
    description: ""
    input: integer
  att fitness:
    label: "Fitness"
    description: ""
    input: integer
  att presence:
    label: "Presence"
    description: ""
    input: integer
  att daring:
    label: "Daring"
    description: ""
    input: integer
  att insight:
    label: "Insight"
    description: ""
    input: integer
  att reason:
    label: "Reason"
    description: ""
    input: integer
  dis command:
    label: "Command"
    description: ""
    input: integer
  dis security:
    label: "Security"
    description: ""
    input: integer
  dis science:
    label: "Science"
    description: ""
    input: integer
  dis conn:
    label: "Conn"
    description: ""
    input: integer
  dis engineering:
    label: "Engineering"
    description: ""
    input: integer
  dis medicine:
    label: "Medicine"
    description: ""
    input: integer
  focuses:
    label: "Focuses"
    description: ""
    input: text
    rows: 20
  talents:
    label: "Talents"
    description: ""
    input: text
    rows: 10
  determination:
    label: "Determination"
    description: ""
    input: integer
    min: 0
    max: 3
  momentum current:
    label: "Momentum Current"
    description: ""
    input: integer
  momentum max:
    label: "Momentum Max"
    description: ""
    input: integer
  resistance:
    label: "Resistance"
    description: "Resistance (Armor)"
    input: integer
  weapon name 01:
    label: "Weapon Name/Type 01"
    description: "Weapon Name / Type"
    input: string
  weapon skill 01:
    label: "Weapon Skill 01"
    description: "Weapon Skill"
    input: integer
  weapon qualities 01:
    label: "Weapon Qualities 01"
    description: "Weapon Qualities"
    input: string
  weapon name 02:
    label: "Weapon Name/Type 02"
    description: "Weapon Name / Type"
    input: string
  weapon skill 02:
    label: "Weapon Skill 02"
    description: "Weapon Skill"
    input: integer
  weapon qualities 02:
    label: "Weapon Qualities 02"
    description: "Weapon Qualities"
    input: string
  weapon name 03:
    label: "Weapon Name/Type 03"
    description: "Weapon Name / Type"
    input: string
  weapon skill 03:
    label: "Weapon Skill 03"
    description: "Weapon Skill"
    input: integer
  weapon qualities 03:
    label: "Weapon Qualities 03"
    description: "Weapon Qualities"
    input: string
  weapon name 04:
    label: "Weapon Name/Type 04"
    description: "Weapon Name / Type"
    input: string
  weapon skill 04:
    label: "Weapon Skill 04"
    description: "Weapon Skill"
    input: integer
  weapon qualities 04:
    label: "Weapon Qualities 04"
    description: "Weapon Qualities"
    input: string
  weapon name 05:
    label: "Weapon Name/Type 05"
    description: "Weapon Name / Type"
    input: string
  weapon skill 05:
    label: "Weapon Skill 05"
    description: "Weapon Skill"
    input: integer
  weapon qualities 05:
    label: "Weapon Qualities 05"
    description: "Weapon Qualities"
    input: string
  weapon name 06:
    label: "Weapon Name/Type 06"
    description: "Weapon Name / Type"
    input: string
  weapon skill 06:
    label: "Weapon Skill 06"
    description: "Weapon Skill"
    input: integer
  weapon qualities 06:
    label: "Weapon Qualities 06"
    description: "Weapon Qualities"
    input: string
  weapon name 07:
    label: "Weapon Name/Type 07"
    description: "Weapon Name / Type"
    input: string
  weapon skill 07:
    label: "Weapon Skill 07"
    description: "Weapon Skill"
    input: integer
  weapon qualities 07:
    label: "Weapon Qualities 07"
    description: "Weapon Qualities"
    input: string
  weapon name 08:
    label: "Weapon Name/Type 08"
    description: "Weapon Name / Type"
    input: string
  weapon skill 08:
    label: "Weapon Skill 08"
    description: "Weapon Skill"
    input: integer
  weapon qualities 08:
    label: "Weapon Qualities 08"
    description: "Weapon Qualities"
    input: string
    weapon name 09:
    label: "Weapon Name/Type 09"
    description: "Weapon Name / Type"
    input: string
  weapon skill 09:
    label: "Weapon Skill 09"
    description: "Weapon Skill"
    input: integer
  weapon qualities 09:
    label: "Weapon Qualities 09"
    description: "Weapon Qualities"
    input: string
  weapon name 10:
    label: "Weapon Name/Type 10"
    description: "Weapon Name / Type"
    input: string
  weapon skill 10:
    label: "Weapon Skill 10"
    description: "Weapon Skill"
    input: integer
  weapon qualities 10:
    label: "Weapon Qualities 10"
    description: "Weapon Qualities"
    input: string
  other equipment:
    label: "Other Equipment"
    description: "Your belongings"
    input: text
    rows: 30
  stress max:
    label: "Stress Max"
    description: ""
    input: integer
  stress current:
    label: "Stress Current"
    description: ""
    input: integer
  injuries:
    label: "Injuries"
    description: ""
    input: text
    rows: 5
  notes: 
    label: "Notes"
    description: "Notes"
    input: text
    rows: 10
  col ships:
    label: "col ships"
    input: text
    rows: 2
    description: "The space ships you possess"
    placeholder: "enter the block ids of your ships, separated by comma"
