fields:
# sheet: my mini sheet
    # row
        # col: col-12
            # card: personal: Personal Data
                # card-body
                    # table
    name:
        label: "Name"
        input: string
        required: true
        placeholder: "Name of the hero"
    class:
        label: "Class"
        input: select
        options:
            warrior: warrior
            mage: mage
            thief: thief
    level:
        label: "Level"
        input: number
    species:
        label: "Species"
        input: string
    profession:
        label: "Profession"
        input: string
    portrait:
        label: "Portrait"
        input: integer
        render: image
                    # /table
                # /card-body
            # /card
        # /col
    # /row
    # row
        # col: col-12 col-md-4
            # card: brawn
                # card-body
    # dots: 10
    brawn:
        label: "brawn"
        input: string
                # /card-body
            # /card
        # /col
    # dots: 10
        # col: col-12 col-md-4
            # card: agility
                # card-body
    agility:
        label: "agility"
        input: string
                # /card-body
            # /card
        # /col
    # dots: 10
        # col: col-12 col-md-4
            # card: vitality
                # card-body
    vitality:
        label: "vitality"
        input: string
                # /card-body
            # /card
        # /col
    # /row
    # row
        # col: col-12 col-md-6
            # card: belongings: Inventory
                # card-body
                    # table: horiz
                        # iter: 15
    item name:
        label: "item name"
        input: string
    item weight:
        label: "item weight"
        input: integer
    item stowed:
        label: "item stowed"
        input: checkbox
                        # /iter
                    # /table
                # /card-body
            # /card
        # /col
        # col: col-12 col-md-6
            # card: weapons: Weapons
                # card-body
                    # table: horiz: nosplit
                        # iter: 5
    weapon name:
        label: "weapon name"
        input: string
    weapon weight:
        label: "weapon weight"
        input: integer
    weapon stowed:
        label: "weapon stowed"
        input: checkbox
                        # /iter
                    # /table
                # /card-body
            # /card
            # card: armor: Armor
                # card-body
                    # table:
                        # iter: 5
    armor name:
        label: "armor name"
        input: string
    armor weight:
        label: "armor weight"
        input: integer
    armor stowed:
        label: "armor stowed"
        input: checkbox
                        # /iter
                    # /table
                # /card-body
            # /card
        # /col
        # col: col-12
            # card: notes: Character notes 
                # card-body: mention
    notes:
        label: "notes"
        input: text
        rows: 3
                # /card-body
            # /card
        # /col
    # /row
# /sheet