# sheet: capharnaum
fields:
  ###! --- section 1 ----------------
  # row
    # col: col-12 col-md-8
      # card: personal: Personal Information
        # card-body
          # table
  name:
    label: "Name"
    input: string
    placeholder: "Name of the hero"
    description: "This is the name of your hero."
    required: true
  path:
    label: "Path"
    input: string
    required: true
  blood:
    label: "Blood"
    input: string
    required: true
  status:
    label: "Status"
    input: string
    required: true
  occupation:
    label: "Occupation"
    input: string
    required: true
          # /table
        # /card-body
      # /card
    # /col
    # col: col-4 col-lg-4 hidden-xs hidden-sm hidden-md d-none d-lg-block
      # card: portrait: Portrait
        # card-body
  portrait:
    label: "Portrait"
    input: integer
    render: image
        # /card-body
      # /card
    # /col
  # /row
  ###! --- section 2 ----------------
  # row
    # col: col-12 col-md-8
      # card: basics: Attributes
        # card-body
          # row
            # col: col-12 col-md-6 col-lg-3
              # card: strength
                # card-body
  strength:
    label: "Strength"
    input: integer
    required: true
                # /card-body
              # /card
            # /col
            # col: col-12 col-md-6 col-lg-3
              # card: constitution
                # card-body
  constitution:
    label: "Constitution"
    input: integer
    required: true
                # /card-body
              # /card
            # /col
            # col: col-12 col-md-6 col-lg-3
              # card: dexterity
                # card-body
  dexterity:
    label: "Dexterity"
    input: integer
    required: true
                # /card-body
              # /card
            # /col
            # col: col-12 col-md-6 col-lg-3
              # card: intelligence
                # card-body
  intelligence:
    label: "Intelligence"
    input: integer
    required: true
                # /card-body
              # /card
            # /col
            # col: col-12 col-md-6 col-lg-3
              # card: charisma
                # card-body
  charisma:
    label: "Charisma"
    input: integer
    required: true
                # /card-body
              # /card
            # /col
            # col: col-12 col-md-6 col-lg-3
              # card: charisma
                # card-body
  heroism:
    label: "Heroism"
    input: integer
                # /card-body
              # /card
            # /col
            # col: col-12 col-md-6 col-lg-9
              # card: x
                # card-body
                  # row
                    # col: col-12 col-md-6 col-lg-3
                      # card: x
                        # card-body
                          # table
  bravery:
    label: "Bravery"
    input: integer
  bravery stars:
    label: "Bravery Stars"
    input: integer
  faith:
    label: "Faith"
    input: integer
  faith stars:
    label: "Faith Stars"
    input: integer
  loyalty:
    label: "Loyalty"
    input: integer
  loyalty stars:
    label: "Loyalty Stars"
    input: integer
                          # /table
                        # /card-body
                      # /card
                    # /col
                  # /row
                # /col
              # /row
            # /col
          # /row
          # row
            # col: col-12
              # card: special
                # card-body
                  # row
                    # col: col-12 col-md-6 col-lg-3
                      # card: x
                        # card-body
  max init:
    label: "Max Init"
    input: integer
                        # /card-body
                      # /card
                    # /col
                    # col: col-12 col-md-6 col-lg-3
                      # card: x
                        # card-body
  dragon dice:
    label: "Dragon Dice"
    input: integer
                        # /card-body
                      # /card
                    # /col
                    # col: col-12 col-md-6 col-lg-3
                      # card: x
                        # card-body
  adventure points:
    label: "Adventure Points"
    input: integer
                        # /card-body
                      # /card
                    # /col
                    # col: col-12 col-md-6 col-lg-3
                      # card: x
                        # card-body
  soak:
    label: "Soak"
    input: integer
                        # /card-body
                      # /card
                    # /col
                  # /row
                # /card-body
              # /card
            # /col
          # /row
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6 col-lg-4
      # card: combat: Combat
        # card-body
  passive defence:
    label: "Passive Defence"
    input: integer
          # row
            # iter: 3
              # col: col-12 col-md-7
                # card: x
                  # card-body
                    # table
  weapon name:
    label: "Weapon Name"
    input: string
                  # /card-body
                # /card
              # /col
              # col: col-12 col-md-5
                # card: x
                  # card-body
  weapon damage:
    label: "Weapon Damage"
    input: integer
                    # /table
                  # /card-body
                # /card
              # /col
            # /iter
          # /row
          # table
  armour:
    label: "Armour"
    input: string
  hit points:
    label: "Hit Points"
    input: integer
          # /table
        # /card-body
      # /card
    # /col
  # /row
  ###! --- section 3 ----------------
  # row
    # col: col-12 col-md-6
      # card: adventurer: Adventurer
        # card-body
          # table
  athletics:
    label: "Athletics"
    input: integer
  riding:
    label: "Riding"
    input: integer
  storytelling:
    label: "Storytelling"
    input: integer
  survival:
    label: "Survival"
    input: integer
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: poet: Poet
        # card-body
          # table
  acting:
    label: "Acting"
    input: integer
  music:
    label: "Music"
    input: integer
  oratory:
    label: "Oratory"
    input: integer
  poetry:
    label: "Poetry"
    input: integer
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: rogue: Rogue
        # card-body
          # table
  assassination:
    label: "Assassination"
    input: integer
  intrusion:
    label: "Intrusion"
    input: integer
  stealth:
    label: "Stealth"
    input: integer
  thievery:
    label: "Thievery"
    input: integer
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: sorcerer: Sorcerer
        # card-body
          # table
  prayer:
    label: "Prayer"
    input: integer
  sacred word:
    label: "Sacred word"
    input: integer
  sacrifice:
    label: "Sacrifice"
    input: integer
  willpower:
    label: "Willpower"
    input: integer
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: labourer: Labourer
        # card-body
          # table
  agriculture:
    label: "Agriculture"
    input: integer
  craft:
    label: "Craft"
    input: integer
  endurance:
    label: "Endurance"
    input: integer
  solidarity:
    label: "Solidarity"
    input: integer
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: prince: Prince
        # card-body
          # table
  elegance:
    label: "Elegance"
    input: integer
  flattery:
    label: "Flattery"
    input: integer
  save face:
    label: "Save Face"
    input: integer
  unctuous bargaining:
    label: "Unctuous Bargaining"
    input: integer
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: sage: Sage
        # card-body
          # table
  history and peoples:
    label: "History and Peoples"
    input: integer
  instruction:
    label: "Instruction"
    input: integer
  notice:
    label: "Notice"
    input: integer
  science:
    label: "Science"
    input: integer
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: warrior: Warrior
        # card-body
          # table
  combat training:
    label: "Combat Training"
    input: integer
  command:
    label: "Command"
    input: integer
  fighting:
    label: "Fighting"
    input: integer
  intimidate:
    label: "Intimidate"
    input: integer
          # /table
        # /card-body
      # /card
    # /col
  # /row
  ###! --- section 4 ----------------
  # row
    # col: col-12 col-md-6
      # card: path-ability: Path Abilities
        # card-body
  path abilities:
    label: "Path Abilities"
    input: text
    rows: 3
  pa level:
    label: "Level"
    input: integer
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: magic: Magic
        # card-body
          # row
            # col
              # card: magic: Sacred Words
                # card-body
                  # table
  create:
    label: "Create"
    input: integer
  transform:
    label: "Transform"
    input: integer
  destroy:
    label: "Destroy"
    input: integer
                  # /table
                # /card-body
              # /card
            # /col
          # /row
  element:
    label: "Element"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
  # /row
  ###! --- section 5 ----------------
  # row
    # col: col-12 col-md-6
      # card: personal-legend: Personal Legend
        # card-body
  personal legend:
    label: "Personal Legend"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: belongings: Equipment
        # card-body
  equipment:
    label: "Equipment"
    input: text
    rows: 3
          # table
  wealth level:
    label: "Wealth Level"
    input: integer
  money:
    label: "Money"
    input: string
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: notes: Notes
        # card-body
  notes:
    label: "Notes"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
  # /row
# /sheet