fields:
  player:
    label: "player"
    input: string
  age:
    label: "age"
    input: string
  race:
    label: "race"
    input: string
  height:
    label: "height"
    input: string
  body type:
    label: "body type"
    input: string
  disabling characteristics:
    label: "disabling characteristics"
    input: string
  str:
    label: "str"
    input: string
  str neg:
    label: "str neg"
    input: checkbox
  ref:
    label: "ref"
    input: string
  ref neg:
    label: "ref neg"
    input: checkbox
  int:
    label: "int"
    input: string
  int neg:
    label: "int neg"
    input: checkbox
  sk endurance:
    label: "sk endurance"
    input: string
  sk athletics:
    label: "sk athletics"
    input: string
  sk grip:
    label: "sk grip"
    input: string
  sk swim:
    label: "sk swim"
    input: string
  sk throw:
    label: "sk throw"
    input: string
  sk perception:
    label: "sk perception"
    input: string
  sk acrobatics:
    label: "sk acrobatics"
    input: string
  sk ride pilot:
    label: "sk ride pilot"
    input: string
  sk sleight of hand:
    label: "sk sleight of hand"
    input: string
  sk stealth:
    label: "sk stealth"
    input: string
  sk general knowledge:
    label: "sk general knowledge"
    input: string
  sk deception:
    label: "sk deception"
    input: string
  sk infiltration:
    label: "sk infiltration"
    input: string
  sk persuasion:
    label: "sk persuasion"
    input: string
  sk survival:
    label: "sk survival"
    input: string
  sk endurance neg:
    label: "sk endurance neg"
    input: checkbox
  sk athletics neg:
    label: "sk athletics neg"
    input: checkbox
  sk grip neg:
    label: "sk grip neg"
    input: checkbox
  sk swim neg:
    label: "sk swim neg"
    input: checkbox
  sk throw neg:
    label: "sk throw neg"
    input: checkbox
  sk perception neg:
    label: "sk perception neg"
    input: checkbox
  sk acrobatics neg:
    label: "sk acrobatics neg"
    input: checkbox
  sk ride pilot neg:
    label: "sk ride pilot neg"
    input: checkbox
  sk sleight of hand neg:
    label: "sk sleight of hand neg"
    input: checkbox
  sk stealth neg:
    label: "sk stealth neg"
    input: checkbox
  sk general knowledge neg:
    label: "sk general knowledge neg"
    input: checkbox
  sk deception neg:
    label: "sk deception neg"
    input: checkbox
  sk infiltration neg:
    label: "sk infiltration neg"
    input: checkbox
  sk persuasion neg:
    label: "sk persuasion neg"
    input: checkbox
  sk survival neg:
    label: "sk survival neg"
    input: checkbox
  sk endurance 3d6:
    label: "sk endurance 3d6"
    input: checkbox
  sk athletics 3d6:
    label: "sk athletics 3d6"
    input: checkbox
  sk grip 3d6:
    label: "sk grip 3d6"
    input: checkbox
  sk swim 3d6:
    label: "sk swim 3d6"
    input: checkbox
  sk throw 3d6:
    label: "sk throw 3d6"
    input: checkbox
  sk perception 3d6:
    label: "sk perception 3d6"
    input: checkbox
  sk acrobatics 3d6:
    label: "sk acrobatics 3d6"
    input: checkbox
  sk ride pilot 3d6:
    label: "sk ride pilot 3d6"
    input: checkbox
  sk sleight of hand 3d6:
    label: "sk sleight of hand 3d6"
    input: checkbox
  sk stealth 3d6:
    label: "sk stealth 3d6"
    input: checkbox
  sk general knowledge 3d6:
    label: "sk general knowledge 3d6"
    input: checkbox
  sk deception 3d6:
    label: "sk deception 3d6"
    input: checkbox
  sk infiltration 3d6:
    label: "sk infiltration 3d6"
    input: checkbox
  sk persuasion 3d6:
    label: "sk persuasion 3d6"
    input: checkbox
  sk survival 3d6:
    label: "sk survival 3d6"
    input: checkbox
  destiny points:
    label: "destiny points"
    input: string
  commerce points:
    label: "commerce points"
    input: string
  injury:
    label: "injury"
    input: text
    rows: 3
  injury count:
    label: "injury count"
    input: string
  inventory equipment:
    label: "inventory equipment"
    input: text
    rows: 3
  notes:
    label: "notes"
    input: text
    rows: 3
  vocation name 01:
    label: "vocation name 01"
    input: string
  vocation skill 01:
    label: "vocation skill 01"
    input: string
  vocation 3d6 01:
    label: "vocation 3d6 01"
    input: checkbox
  vocation attr 01:
    label: "vocation attr 01"
    input: select
    options:
        STR: STR
        REF: REF
        INT: INT
  vocation name 02:
    label: "vocation name 02"
    input: string
  vocation skill 02:
    label: "vocation skill 02"
    input: string
  vocation 3d6 02:
    label: "vocation 3d6 02"
    input: checkbox
  vocation attr 02:
    label: "vocation attr 02"
    input: select
    options:
        STR: STR
        REF: REF
        INT: INT
  vocation name 03:
    label: "vocation name 03"
    input: string
  vocation skill 03:
    label: "vocation skill 03"
    input: string
  vocation 3d6 03:
    label: "vocation 3d6 03"
    input: checkbox
  vocation attr 03:
    label: "vocation attr 03"
    input: select
    options:
        STR: STR
        REF: REF
        INT: INT
  voc skill name 01:
    label: "voc skill name 01"
    input: string
  voc skill 01:
    label: "voc skill 01"
    input: string
  voc attr 01:
    label: "voc attr 01"
    input: select
    options:
        STR: STR
        REF: REF
        INT: INT
  voc 3d6 01:
    label: "voc 3d6 01"
    input: checkbox
  voc skill name 02:
    label: "voc skill name 02"
    input: string
  voc skill 02:
    label: "voc skill 02"
    input: string
  voc attr 02:
    label: "voc attr 02"
    input: select
    options:
        STR: STR
        REF: REF
        INT: INT
  voc 3d6 02:
    label: "voc 3d6 02"
    input: checkbox
  voc skill name 03:
    label: "voc skill name 03"
    input: string
  voc skill 03:
    label: "voc skill 03"
    input: string
  voc attr 03:
    label: "voc attr 03"
    input: select
    options:
        STR: STR
        REF: REF
        INT: INT
  voc 3d6 03:
    label: "voc 3d6 03"
    input: checkbox
  voc skill name 04:
    label: "voc skill name 04"
    input: string
  voc skill 04:
    label: "voc skill 04"
    input: string
  voc attr 04:
    label: "voc attr 04"
    input: select
    options:
        STR: STR
        REF: REF
        INT: INT
  voc 3d6 04:
    label: "voc 3d6 04"
    input: checkbox
  voc skill name 05:
    label: "voc skill name 05"
    input: string
  voc skill 05:
    label: "voc skill 05"
    input: string
  voc attr 05:
    label: "voc attr 05"
    input: select
    options:
        STR: STR
        REF: REF
        INT: INT
  voc 3d6 05:
    label: "voc 3d6 05"
    input: checkbox
  voc skill name 06:
    label: "voc skill name 06"
    input: string
  voc skill 06:
    label: "voc skill 06"
    input: string
  voc attr 06:
    label: "voc attr 06"
    input: select
    options:
        STR: STR
        REF: REF
        INT: INT
  voc 3d6 06:
    label: "voc 3d6 06"
    input: checkbox
  voc skill name 07:
    label: "voc skill name 07"
    input: string
  voc skill 07:
    label: "voc skill 07"
    input: string
  voc attr 07:
    label: "voc attr 07"
    input: select
    options:
        STR: STR
        REF: REF
        INT: INT
  voc 3d6 07:
    label: "voc 3d6 07"
    input: checkbox
  voc skill name 08:
    label: "voc skill name 08"
    input: string
  voc skill 08:
    label: "voc skill 08"
    input: string
  voc attr 08:
    label: "voc attr 08"
    input: select
    options:
        STR: STR
        REF: REF
        INT: INT
  voc 3d6 08:
    label: "voc 3d6 08"
    input: checkbox
  voc skill name 09:
    label: "voc skill name 09"
    input: string
  voc skill 09:
    label: "voc skill 09"
    input: string
  voc attr 09:
    label: "voc attr 09"
    input: select
    options:
        STR: STR
        REF: REF
        INT: INT
  voc 3d6 09:
    label: "voc 3d6 09"
    input: checkbox
  voc skill name 10:
    label: "voc skill name 10"
    input: string
  voc skill 10:
    label: "voc skill 10"
    input: string
  voc attr 10:
    label: "voc attr 10"
    input: select
    options:
        STR: STR
        REF: REF
        INT: INT
  voc 3d6 10:
    label: "voc 3d6 10"
    input: checkbox
  voc skill name 11:
    label: "voc skill name 11"
    input: string
  voc skill 11:
    label: "voc skill 11"
    input: string
  voc attr 11:
    label: "voc attr 11"
    input: select
    options:
        STR: STR
        REF: REF
        INT: INT
  voc 3d6 11:
    label: "voc 3d6 11"
    input: checkbox
  voc skill name 12:
    label: "voc skill name 12"
    input: string
  voc skill 12:
    label: "voc skill 12"
    input: string
  voc attr 12:
    label: "voc attr 12"
    input: select
    options:
        STR: STR
        REF: REF
        INT: INT
  voc 3d6 12:
    label: "voc 3d6 12"
    input: checkbox