# sheet: carphanaum
fields:
  ### --- section 1 ----------------
  # row
  # col: col-12 col-md-8
  # card: social: Personal Information
  # table
  name:
    label: "Name"
    input: string
    placeholder: "Name of the hero"
    description: "This is the name of your hero."
    required: true
  test:
    label: "Test"
    input: select
    options:
      option1:option1
      option2:option2
      option3:option3
  path:
    label: "Path"
    input: string
    required: true
  blood:
    label: "Blood"
    input: string
    required: true
  status:
    label: "Status"
    input: string
    required: true
  occupation:
    label: "Occupation"
    input: string
    required: true
  # /table
  # /card
  # /col
  # col: col-4 col-lg-4 hidden-xs hidden-sm hidden-md d-none d-lg-block
  # card: portrait
  portrait:
    label: "Portrait"
    input: integer
  # /card
  # /col
  # /row
  ### --- section 2 ----------------
  # row
  # col: col-12 col-md-6 col-lg-8
  # card: basics: Attributes
  # group: attributes
  # box
  strength:
    label: "Strength"
    input: integer
    required: true
  # /box
  # box
  constitution:
    label: "Constitution"
    input: integer
    required: true
  # /box
  # box
  dexterity:
    label: "Dexterity"
    input: integer
    required: true
  # /box
  # box
  intelligence:
    label: "Intelligence"
    input: integer
    required: true
  # /box
  # box
  charisma:
    label: "Charisma"
    input: integer
    required: true
  # /box
  # /group
  # group: attributes-other
  # row
  # col: col-12 col-md-6
  heroism:
    label: "Heroism"
    input: integer
  bravery:
    label: "Bravery"
    input: integer
  faith:
    label: "Faith"
    input: integer
  loyalty:
    label: "Loyalty"
    input: integer
  # /col
  # col: col-12 col-md-6
  max init:
    label: "Max Init"
    input: integer
  dragon dice:
    label: "Dragon Dice"
    input: integer
  adventure points:
    label: "Adventure Points"
    input: integer
  soak:
    label: "Soak"
    input: integer
  # /col
  # /row
  # /card
  # /col
  # col: col-12 col-md-6 col-lg-4
  # card: passive-defence: Passive Defence
  # iter: 3
  weapon name:
    label: "Weapon Name"
    input: string
  weapon damage:
    label: "Weapon Damage"
    input: integer
  # /iter
  armour:
    label: "Armour"
    input: integer
  hit points:
    label: "Hit Points"
    input: integer
  # /card
  # /col
  # /row
  ### --- section 3 ----------------
  # row
  # col: col-12 col-md-6
  # card: adventurer
  athletics:
    label: "Athletics"
    input: integer
  riding:
    label: "Riding"
    input: integer
  storytelling:
    label: "Storytelling"
    input: integer
  survival:
    label: "Survival"
    input: integer
  # /card
  # /col
  # col: col-12 col-md-6
  # card: poet
  acting:
    label: "Acting"
    input: integer
  music:
    label: "Music"
    input: integer
  oratory:
    label: "Oratory"
    input: integer
  poetry:
    label: "Poetry"
    input: integer
  # /card
  # /col
  # col: col-12 col-md-6
  # card: rogue
  assassination:
    label: "Assassination"
    input: integer
  intrusion:
    label: "Intrusion"
    input: integer
  stealth:
    label: "Stealth"
    input: integer
  thievery:
    label: "Thievery"
    input: integer
  # /card
  # /col
  # col: col-12 col-md-6
  # card: sorcerer
  prayer:
    label: "Prayer"
    input: integer
  sacred word:
    label: "Sacred word"
    input: integer
  sacrifice:
    label: "Sacrifice"
    input: integer
  willpower:
    label: "Willpower"
    input: integer
  # /card
  # /col
  # col: col-12 col-md-6
  # card: labourer
  agriculture:
    label: "Agriculture"
    input: integer
  craft:
    label: "Craft"
    input: integer
  endurance:
    label: "Endurance"
    input: integer
  solidarity:
    label: "Solidarity"
    input: integer
  # /card
  # /col
  # col: col-12 col-md-6
  # card: prince
  elegance:
    label: "Elegance"
    input: integer
  flattery:
    label: "Flattery"
    input: integer
  save face:
    label: "Save Face"
    input: integer
  unctuous bargaining:
    label: "Unctuous Bargaining"
    input: integer
  # /card
  # /col
  # col: col-12 col-md-6
  # card: sage
  history and peoples:
    label: "History and Peoples"
    input: integer
  instruction:
    label: "Instruction"
    input: integer
  notice:
    label: "Notice"
    input: integer
  science:
    label: "Science"
    input: integer
  # /card
  # /col
  # col: col-12 col-md-6
  # card: warrior
  combat training:
    label: "Combat Training"
    input: integer
  command:
    label: "Command"
    input: integer
  fighting:
    label: "Fighting"
    input: integer
  intimidate:
    label: "Intimidate"
    input: integer
  # /card
  # /col
  # /row
  ### --- section 4 ----------------
  # row
  # col: col-12 col-md-6
  # card: path-ability
  path ability:
    label: "Path Ability"
    input: integer
  pa level:
    label: "Level"
    input: integer
  # /card
  # /col
  # col: col-12 col-md-6
  # card: magic
  sacred word create:
    label: "Sacred Word Create"
    input: integer
  sacred word transform:
    label: "Sacred Word Transform"
    input: integer
  sacred word destroy:
    label: "Sacred Word Destroy"
    input: integer
  # iter: 18
  element name:
    label: "Element Name"
    input: integer
  element type:
    label: "Element Type"
    input: integer
  # /iter
  # /card
  # /col
  # /row
  ### --- section 5 ----------------
  # row
  # col: col-12 col-md-6
  # card: personal-legend
  personal legend:
    label: "Personal Legend"
    input: text
    rows: 3
  # /card
  # /col
  # col: col-12 col-md-6
  # card: belongings
  equipment:
    label: "Equipment"
    input: text
    rows: 3
  wealth level:
    label: "Wealth Level"
    input: integer
  money:
    label: "Money"
    input: integer
  # /card
  # /col
  # /row
# /sheet