# sheet: dragonbane
### logo: /uploads/images/18484251b1a6aae0556f9af38af90fa9.webp
fields:
  # row
    # col: col-12 col-md-4
      # card: personal
        # card-body
          # table
  name:
    label: "name"
    input: string
    required: true
  player:
    label: "player"
    input: string
  kin:
    label: "kin"
    input: string
    required: true
  age:
    label: "age"
    input: string
  profession:
    label: "profession"
    input: string
    required: true
  weakness:
    label: "weakness"
    input: string
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4
      # card: appearance
        # card-body
  appearance:
    label: "appearance"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4
      # card: portrait
        # card-body
  imageid:
    label: "imageid"
    input: integer
    render: image
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: attributes
        # card-body
          # row
            # col: col-6 col-md-2
  att str:
    label: "att str"
    input: string
    required: true
  cond exhausted:
    label: "cond exhausted"
    input: checkbox
            # /col
            # col: col-6 col-md-2
  att con:
    label: "att con"
    input: string
    required: true
  cond sickly:
    label: "cond sickly"
    input: checkbox
            # /col
            # col: col-6 col-md-2
  att agl:
    label: "att agl"
    input: string
    required: true
  cond dazed:
    label: "cond dazed"
    input: checkbox
            # /col
            # col: col-6 col-md-2
  att int:
    label: "att int"
    input: string
    required: true
  cond angry:
    label: "cond angry"
    input: checkbox
            # /col
            # col: col-6 col-md-2
  att wil:
    label: "att wil"
    input: string
    required: true
  cond scared:
    label: "cond scared"
    input: checkbox
            # /col
            # col: col-6 col-md-2
  att cha:
    label: "att cha"
    input: string
    required: true
  cond disheartened:
    label: "cond disheartened"
    input: checkbox
            # /col
          # /row
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-3
      # card: dmg bonus str
        # card-body
          # table
  dmg bonus str:
    label: "dmg bonus str"
    input: string
  dmg bonus agl:
    label: "dmg bonus agl"
    input: string
  movement:
    label: "movement"
    input: string
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-3
      # card: misc
        # card-body
  abilities:
    label: "abilities"
    input: text
    rows: 3
          # table
  gold:
    label: "gold"
    input: integer
  silver:
    label: "silver"
    input: integer
  copper:
    label: "copper"
    input: integer
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: skills
        # card-body
          # table: horiz
            # iter: 20
  skill name:
    label: "skill name"
    input: string
  skill att:
    label: "skill att"
    input: select
    options:
      agl: agl
      cha: cha
      int: int
      str: str
  skill value:
    label: "skill value"
    input: string
  skill check:
    label: "skill check"
    input: checkbox
            # /iter
            # iter: 10
  weapon skill name:
    label: "weapon skill name"
    input: string
  weapon skill att:
    label: "weapon skill att"
    input: select
    options:
      agl: agl
      cha: cha
      int: int
      str: str
  weapon skill value:
    label: "weapon skill value"
    input: string
  weapon skill check:
    label: "weapon skill check"
    input: checkbox
            # /iter
            # iter: 10
  sec skill name:
    label: "skill sec name"
    input: string
  sec skill att:
    label: "skill sec att"
    input: select
    options:
      agl: agl
      cha: cha
      int: int
      str: str
  sec skill value:
    label: "skill sec value"
    input: string
  sec skill check:
    label: "skill sec check"
    input: checkbox
            # /iter
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-3
      # card: belongings
        # card-body
          # table
  enc limit:
    label: "enc limit"
    input: string
  backpack:
    label: "backpack"
    input: checkbox
          # /table
          # table
            # iter: 10
  equipment:
    label: "equipment"
    input: string
            # /iter
          # /table
          # table
  memento:
    label: "memento"
    input: text
    rows: 3
          # /table
          # table
  tiny items:
    label: "tiny items"
    input: text
    rows: 3
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-6
      # row
        # col: col-12 col-md-6
          # card: armor
            # card-body
              # table
  armor rating:
    label: "armor rating"
    input: integer
  armor name:
    label: "armor name"
    input: string
  armor bane acrobatics:
    label: "armor bane acrobatics"
    input: checkbox
  armor bane evade:
    label: "armor bane evade"
    input: checkbox
  armor bane sneaking:
    label: "armor bane sneaking"
    input: checkbox
              # /table
            # /card-body
          # /card
        # /col
        # col: col-12 col-md-6
          # card: helmet
            # card-body
              # table
  helmet rating:
    label: "helmet rating"
    input: integer
  helmet name:
    label: "helmet name"
    input: string
  helmet bane awareness:
    label: "helmet bane awareness"
    input: checkbox
  helmet bane bows:
    label: "helmet bane bows"
    input: checkbox
              # /table
            # /card-body
          # /card
        # /col
        # col: col-12
          # card: weapons
            # card-body
              # table: horiz
                # iter: 3
  weapon name:
    label: "weapon name"
    input: string
  weapon grip:
    label: "weapon grip"
    input: string
  weapon range:
    label: "weapon range"
    input: string
  weapon damage:
    label: "weapon damage"
    input: string
  weapon durability:
    label: "weapon durability"
    input: string
  weapon features:
    label: "weapon features"
    input: string
                # /iter
              # /table
            # /card-body
          # /card
        # /col
      # /row
    # /col
    # col: col-12 col-md-4
      # card: notes
        # card-body
          # row
            # col: col-12
              # table
  wil points:
    label: "wil points"
    input: integer
  wil points max:
    label: "wil points max"
    input: integer
              # /table
            # /col
          # /row
          # row
            # col: col-12
              # table
  hit points:
    label: "hit points"
    input: integer
  hit points max:
    label: "hit points max"
    input: integer
              # /table
            # /col
          # /row
          # row
            # col: col-12
              # table
  dr s1:
    label: "dr s1"
    input: checkbox
  dr f1:
    label: "dr f1"
    input: checkbox
  dr s2:
    label: "dr s2"
    input: checkbox
  dr f2:
    label: "dr f2"
    input: checkbox
  dr s3:
    label: "dr s3"
    input: checkbox
  dr f3:
    label: "dr f3"
    input: checkbox
              # /table
            # /col
          # /row
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: notes
        # card-body
  notes:
    label: "notes"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
  # /row
# /sheet