# sheet: call of cthulhu monster
fields:
  # row
    # col: col-12
      # card: title: xxx
        # card-body
  name:
    label: "name"
    input: string
    required: true
  additional:
    label: "additional"
    input: string
  shortdesc:
    label: "shortdesc"
    input: text
    rows: 3
  imageid:
    label: "imageid"
    input: integer
    render: image
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: attributes
        # card-body
          # row
            # col: col-6 col-md-3
  str:
    label: "str"
    input: string
            # /col
            # col: col-6 col-md-3
  con:
    label: "con"
    input: string
            # /col
            # col: col-6 col-md-3
  siz:
    label: "siz"
    input: string
            # /col
            # col: col-6 col-md-3
  dex:
    label: "dex"
    input: string
            # /col
            # col: col-6 col-md-3
  int:
    label: "int"
    input: string
            # /col
            # col: col-6 col-md-3
  app:
    label: "app"
    input: string
            # /col
            # col: col-6 col-md-3
  pow:
    label: "pow"
    input: string
            # /col
            # col: col-6 col-md-3
  edu:
    label: "edu"
    input: string
            # /col
          # /row
          # row
            # col: col-6 col-md-3
  san:
    label: "san"
    input: string
            # /col
            # col: col-6 col-md-3
  hp:
    label: "hp"
    input: string
            # /col
            # col: col-6 col-md-3
  db:
    label: "db"
    input: string
            # /col
            # col: col-6 col-md-3
  build:
    label: "build"
    input: string
            # /col
          # /row
          # row
            # col: col-6 col-md-3
  move:
    label: "move"
    input: string
            # /col
            # col: col-6 col-md-3
  mp:
    label: "mp"
    input: string
            # /col
            # col: col-6 col-md-3
  luck:
    label: "luck"
    input: string
            # /col
          # /row
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: combat: Combat
        # card-body
  attacks:
    label: "attacks"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: skills: Skills
        # card-body
  skills:
    label: "skills"
    input: text
    rows: 3
  armor:
    label: "armor"
    input: text
    rows: 3
  spells:
    label: "spells"
    input: text
    rows: 3
  sanity loss:
    label: "sanity loss"
    input: string
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: title
        # card-body
  longdesc:
    label: "longdesc"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
  # /row
# /sheet