# sheet: my mini sheet
fields:
    # row
        # col: col-12
            # card: personal: Personal Data
                # card-body
    name:
        label: "name"
        input: string
        required: true
        placeholder: "Name of the hero"
    class:
        label: "class"
        input: select
        options:
            warrior: warrior
            mage: mage
            thief: thief
    level:
        label: "level"
        input: number
                # /card-body
            # /card
        # /col
        # col: col-12 col-md-6
            # card: belongings: Inventory
                # card-body
                    # table: horiz
                        # iter: 15
    item name:
        label: "item name"
        input: string
    item weight:
        label: "item weight"
        input: integer
    item stowed:
        label: "item stowed"
        input: checkbox
                        # /iter
                    # /table
                # /card-body
            # /card
        # /col
        # col: col-12
            # card: notes: Character notes 
                # card-body: mention
    notes:
        label: "notes"
        input: text
        rows: 3
                # /card-body
            # /card
        # /col
    # /row
# /sheet