# sheet: fantasy age character
fields:
  # row
    # col: col-12 col-md-8
      # card: personal: Personal Information
        # card-body
          # table
  name:
    label: "name"
    input: string
  class:
    label: "class"
    input: string
    placeholder: "eg Mage, Warrior, Rogue"
  level:
    label: "level"
    input: integer
  species:
    label: "species"
    input: string
    placeholder: "eg Gnome"
  social class:
    label: "social class"
    input: string
  background:
    label: "background"
    input: string
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4
      # card: portrait: Portrait
        # card-body
  imageid:
    label: "imageid"
    input: integer
    render: image
        # /card-body
      # /card
    # /col
  # /row
  # row
    # iter: 9
      # col: col-12 col-md-6 col-lg-4
        # card: attribute: Attribute
          # card-body
  att rating:
    label: "att rating"
    input: integer
  attr primary:
    label: "attr primary"
    input: checkbox
          # /card-body
        # /card
        # card: foci: Foci
          # card-body
  attr focus:
    label: "attr focus"
    input: text
    row: 3
          # /card-body
        # /card
      # /col
    # /iter
  # /row
  # row
    # col: col-12 col-md-3
      # card: initiative: Initiative
        # card-body
  initiative:
    label: "initiative"
    input: integer
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-3
      # card: hp: HP
        # card-body
  hp curr:
    label: "hp curr"
    input: integer
  hp max:
    label: "hp max"
    input: integer
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-3
      # card: mp: MP
        # card-body
  mp curr:
    label: "mp curr"
    input: integer
  mp max:
    label: "mp max"
    input: integer
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-3
      # card: xp: XP
        # card-body
  xp:
    label: "xp"
    input: integer
  xp next:
    label: "xp next"
    input: integer
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-4
      # card: speed: Base Speed
        # card-body
  speed base:
    label: "speed base"
    input: integer
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4
      # card: shield bonus: Shield Bonus
        # card-body
  shield bonus:
    label: "shield bonus"
    input: integer
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4
      # card: armor: Armor
        # card-body
  armor:
    label: "armor"
    input: integer
  armor penalty:
    label: "armor penalty"
    input: integer
  armor type:
    label: "armor type"
    input: string
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-12
      # card: weapons: Weapons
        # card-body
  weapon groups:
    label: "weapon groups"
    input: string
    placeholder: "eg Brawling, Light Blades"
          # table: horiz
            # iter: 6
  weapon name:
    label: "weapon name"
    input: string
  weapon att:
    label: "weapon att"
    input: string
  weapon dmg:
    label: "weapon dmg"
    input: string
  weapon rng:
    label: "weapon rng"
    input: string
  weapon reload:
    label: "weapon reload"
    input: string
  weapon ammo:
    label: "weapon ammo"
    input: integer
            # /iter
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-12 col-lg-12
      # card: spells: Spells
        # card-body
          # table: horiz
            # iter: 10
  spell name:
    label: "spell name"
    input: string
  spell arcana:
    label: "spell arcana"
    input: string
  spell type:
    label: "spell type"
    input: string
  spell cost:
    label: "spell cost"
    input: integer
  spell cast time:
    label: "spell cast time"
    input: string
  spell tn:
    label: "spell tn"
    input: integer
  spell test:
    label: "spell test"
    input: string
  spell desc:
    label: "spell desc"
    input: text
    rows: 3
            # /iter
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: powers: Powers
        # card-body
          # table: horiz
            # iter: 6
  power type:
    label: "power type"
    input: string
  power short:
    label: "power short"
    input: string
  power desc:
    label: "power desc"
    input: string
            # /iter
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: talents: Talents
        # card-body
          # table: horiz
            # iter: 10
  talent degree:
    label: "talent degree"
    input: select
    options:
      novice: novice
      journeyman: journeyman
      master: master
  talent name:
    label: "talent name"
    input: string
  talent desc:
    label: "talent desc"
    input: string
  talent novice:
    label: "talent novice"
    input: text
    rows: 3
  talent journeyman:
    label: "talent journeyman"
    input: text
    rows: 3
  talent master:
    label: "talent master"
    input: text
    rows: 3
            # /iter
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: specializations: Spezializations
        # card-body
          # table: horiz
            # iter: 10
  specialization degree:
    label: "specialization degree"
    input: select
    options:
      novice: novice
      journeyman: journeyman
      master: master
  specialization name:
    label: "specialization name"
    input: string
  specialization desc:
    label: "specialization desc"
    input: string
  specialization novice:
    label: "specialization novice"
    input: text
    rows: 3
  specialization journeyman:
    label: "specialization journeyman"
    input: text
    rows: 3
  specialization master:
    label: "specialization master"
    input: text
    rows: 3
            # /iter
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-6
      # card: belongings: Equipment
        # card-body
  gold:
    label: "gold"
    input: integer
  silver:
    label: "silver"
    input: integer
  copper:
    label: "copper"
    input: integer
  equipment:
    label: "equipment"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: appearance: Appearance
        # card-body
  appearance:
    label: "appearance"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: goals: Goals
        # card-body
  goals:
    label: "goals"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: relationships: Relationships
        # card-body
  relationships:
    label: "relationships"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-12
      # card: notes: Notes
        # card-body
  notes:
    label: "notes"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
  # /row
# /sheet