fields:
  imageid:
    label: "imageid"
    input: integer
  career:
    label: "career"
    input: string
    required: true
  appearance:
    label: "appearance"
    input: text
    rows: 3
  personal agenda:
    label: "personal agenda"
    input: text
    rows: 3
  buddy:
    label: "buddy"
    input: string
  rival:
    label: "rival"
    input: string
  talents:
    label: "talents"
    input: text
    rows: 3
  injuries:
    label: "injuries"
    input: text
    rows: 3
  cond starving:
    label: "cond starving"
    input: checkbox
  cond dehydrated:
    label: "cond dehydrated"
    input: checkbox
  cond exhausted:
    label: "cond exhausted"
    input: checkbox
  cond freezing:
    label: "cond freezing"
    input: checkbox
  experience:
    label: "experience"
    input: string
  notes:
    label: "notes"
    input: text
    rows: 3
  gear:
    label: "gear"
    input: text
    rows: 3
  armor name:
    label: "armor name"
    input: string
  armor rating:
    label: "armor rating"
    input: string
  stress:
    label: "stress"
    input: string
  att strength:
    label: "att strength"
    input: string
    required: true
  att agility:
    label: "att agility"
    input: string
    required: true
  att wits:
    label: "att wits"
    input: string
    required: true
  att empathy:
    label: "att empathy"
    input: string
    required: true
  skill name 01:
    label: "skill name 01"
    input: string
  skill att 01:
    label: "skill att 01"
    input: select
    options:
      strength: strength
      agility: agility
      wits: wits
      empathy: empathy
  skill value 01:
    label: "skill value 01"
    input: string
  skill name 02:
    label: "skill name 02"
    input: string
  skill att 02:
    label: "skill att 02"
    input: select
    options:
      strength: strength
      agility: agility
      wits: wits
      empathy: empathy
  skill value 02:
    label: "skill value 02"
    input: string
  skill name 03:
    label: "skill name 03"
    input: string
  skill att 03:
    label: "skill att 03"
    input: select
    options:
      strength: strength
      agility: agility
      wits: wits
      empathy: empathy
  skill value 03:
    label: "skill value 03"
    input: string
  skill name 04:
    label: "skill name 04"
    input: string
  skill att 04:
    label: "skill att 04"
    input: select
    options:
      strength: strength
      agility: agility
      wits: wits
      empathy: empathy
  skill value 04:
    label: "skill value 04"
    input: string
  skill name 05:
    label: "skill name 05"
    input: string
  skill att 05:
    label: "skill att 05"
    input: select
    options:
      strength: strength
      agility: agility
      wits: wits
      empathy: empathy
  skill value 05:
    label: "skill value 05"
    input: string
  skill name 06:
    label: "skill name 06"
    input: string
  skill att 06:
    label: "skill att 06"
    input: select
    options:
      strength: strength
      agility: agility
      wits: wits
      empathy: empathy
  skill value 06:
    label: "skill value 06"
    input: string
  skill name 07:
    label: "skill name 07"
    input: string
  skill att 07:
    label: "skill att 07"
    input: select
    options:
      strength: strength
      agility: agility
      wits: wits
      empathy: empathy
  skill value 07:
    label: "skill value 07"
    input: string
  skill name 08:
    label: "skill name 08"
    input: string
  skill att 08:
    label: "skill att 08"
    input: select
    options:
      strength: strength
      agility: agility
      wits: wits
      empathy: empathy
  skill value 08:
    label: "skill value 08"
    input: string
  skill name 09:
    label: "skill name 09"
    input: string
  skill att 09:
    label: "skill att 09"
    input: select
    options:
      strength: strength
      agility: agility
      wits: wits
      empathy: empathy
  skill value 09:
    label: "skill value 09"
    input: string
  skill name 10:
    label: "skill name 10"
    input: string
  skill att 10:
    label: "skill att 10"
    input: select
    options:
      strength: strength
      agility: agility
      wits: wits
      empathy: empathy
  skill value 10:
    label: "skill value 10"
    input: string
  skill name 11:
    label: "skill name 11"
    input: string
  skill att 11:
    label: "skill att 11"
    input: select
    options:
      strength: strength
      agility: agility
      wits: wits
      empathy: empathy
  skill value 11:
    label: "skill value 11"
    input: string
  skill name 12:
    label: "skill name 12"
    input: string
  skill att 12:
    label: "skill att 12"
    input: select
    options:
      strength: strength
      agility: agility
      wits: wits
      empathy: empathy
  skill value 12:
    label: "skill value 12"
    input: string
  weapon name 01:
    label: "weapon name 01"
    input: string
  weapon damage 01:
    label: "weapon damage 01"
    input: string
  weapon range 01:
    label: "weapon range 01"
    input: string
  weapon bonus 01:
    label: "weapon bonus 01"
    input: string
  weapon name 02:
    label: "weapon name 02"
    input: string
  weapon damage 02:
    label: "weapon damage 02"
    input: string
  weapon range 02:
    label: "weapon range 02"
    input: string
  weapon bonus 02:
    label: "weapon bonus 02"
    input: string
  weapon name 03:
    label: "weapon name 03"
    input: string
  weapon damage 03:
    label: "weapon damage 03"
    input: string
  weapon range 03:
    label: "weapon range 03"
    input: string
  weapon bonus 03:
    label: "weapon bonus 03"
    input: string
  weapon name 04:
    label: "weapon name 04"
    input: string
  weapon damage 04:
    label: "weapon damage 04"
    input: string
  weapon range 04:
    label: "weapon range 04"
    input: string
  weapon bonus 04:
    label: "weapon bonus 04"
    input: string
  health:
    label: "health"
    input: string
  radiation:
    label: "radiation"
    input: string
  consum air:
    label: "consum air"
    input: string
  consum food:
    label: "consum food"
    input: string
  consum power:
    label: "consum power"
    input: string
  consum water:
    label: "consum water"
    input: string
  tiny items:
    label: "tiny items"
    input: text
    rows: 3
  signature item:
    label: "signature item"
    input: string
  encumbrance:
    label: "encumbrance"
    input: string
