fields:
  age:
    label: "age"
    input: string
  imageid:
    label: "imageid"
    input: integer
  archetype:
    label: "archetype"
    input: string
    required: true
  motivation:
    label: "motivation"
    input: string
  trauma:
    label: "trauma"
    input: string
  dark secret:
    label: "dark secret"
    input: string
  rel pc1:
    label: "rel pc1"
    input: string
  rel pc2:
    label: "rel pc2"
    input: string
  rel pc3:
    label: "rel pc3"
    input: string
  rel pc4:
    label: "rel pc4"
    input: string
  talents:
    label: "talents"
    input: text
    rows: 3
  insights:
    label: "insights"
    input: text
    rows: 3
  advantages:
    label: "advantages"
    input: text
    rows: 3
  memento:
    label: "memento"
    input: text
    rows: 3
  att physique:
    label: "att physique"
    input: string
    required: true
  att precision:
    label: "att precision"
    input: string
    required: true
  att logic:
    label: "att logic"
    input: string
    required: true
  att empathy:
    label: "att empathy"
    input: string
    required: true
  resources:
    label: "resources"
    input: string
  cond physical:
    label: "cond physical"
    input: select
    options:
      none: none
      exhausted: exhausted
      battered: battered
      wounded: wounded
      broken: broken
  cond mental:
    label: "cond mental"
    input: select
    options:
      none: none
      angry: angry
      frightened: frightened
      hopeless: hopeless
      broken: broken
  experience:
    label: "experience"
    input: string
  equipment name 01:
    label: "equipment name 01"
    input: string
  equipment bonus 01:
    label: "equipment bonus 01"
    input: string
  equipment name 02:
    label: "equipment name 02"
    input: string
  equipment bonus 02:
    label: "equipment bonus 02"
    input: string
  equipment name 03:
    label: "equipment name 03"
    input: string
  equipment bonus 03:
    label: "equipment bonus 03"
    input: string
  equipment name 04:
    label: "equipment name 04"
    input: string
  equipment bonus 04:
    label: "equipment bonus 04"
    input: string
  equipment name 05:
    label: "equipment name 05"
    input: string
  equipment bonus 05:
    label: "equipment bonus 05"
    input: string
  equipment name 06:
    label: "equipment name 06"
    input: string
  equipment bonus 06:
    label: "equipment bonus 06"
    input: string
  equipment name 07:
    label: "equipment name 07"
    input: string
  equipment bonus 07:
    label: "equipment bonus 07"
    input: string
  equipment name 08:
    label: "equipment name 08"
    input: string
  equipment bonus 08:
    label: "equipment bonus 08"
    input: string
  equipment name 09:
    label: "equipment name 09"
    input: string
  equipment bonus 09:
    label: "equipment bonus 09"
    input: string
  equipment name 10:
    label: "equipment name 10"
    input: string
  equipment bonus 10:
    label: "equipment bonus 10"
    input: string
  skill name 01:
    label: "skill name 01"
    input: string
  skill att 01:
    label: "skill att 01"
    input: select
    options:
      physique: physique
      precision: precision
      logic: logic
      empathy: empathy
  skill value 01:
    label: "skill value 01"
    input: string
  skill name 02:
    label: "skill name 02"
    input: string
  skill att 02:
    label: "skill att 02"
    input: select
    options:
      physique: physique
      precision: precision
      logic: logic
      empathy: empathy
  skill value 02:
    label: "skill value 02"
    input: string
  skill name 03:
    label: "skill name 03"
    input: string
  skill att 03:
    label: "skill att 03"
    input: select
    options:
      physique: physique
      precision: precision
      logic: logic
      empathy: empathy
  skill value 03:
    label: "skill value 03"
    input: string
  skill name 04:
    label: "skill name 04"
    input: string
  skill att 04:
    label: "skill att 04"
    input: select
    options:
      physique: physique
      precision: precision
      logic: logic
      empathy: empathy
  skill value 04:
    label: "skill value 04"
    input: string
  skill name 05:
    label: "skill name 05"
    input: string
  skill att 05:
    label: "skill att 05"
    input: select
    options:
      physique: physique
      precision: precision
      logic: logic
      empathy: empathy
  skill value 05:
    label: "skill value 05"
    input: string
  skill name 06:
    label: "skill name 06"
    input: string
  skill att 06:
    label: "skill att 06"
    input: select
    options:
      physique: physique
      precision: precision
      logic: logic
      empathy: empathy
  skill value 06:
    label: "skill value 06"
    input: string
  skill name 07:
    label: "skill name 07"
    input: string
  skill att 07:
    label: "skill att 07"
    input: select
    options:
      physique: physique
      precision: precision
      logic: logic
      empathy: empathy
  skill value 07:
    label: "skill value 07"
    input: string
  skill name 08:
    label: "skill name 08"
    input: string
  skill att 08:
    label: "skill att 08"
    input: select
    options:
      physique: physique
      precision: precision
      logic: logic
      empathy: empathy
  skill value 08:
    label: "skill value 08"
    input: string
  skill name 09:
    label: "skill name 09"
    input: string
  skill att 09:
    label: "skill att 09"
    input: select
    options:
      physique: physique
      precision: precision
      logic: logic
      empathy: empathy
  skill value 09:
    label: "skill value 09"
    input: string
  skill name 10:
    label: "skill name 10"
    input: string
  skill att 10:
    label: "skill att 10"
    input: select
    options:
      physique: physique
      precision: precision
      logic: logic
      empathy: empathy
  skill value 10:
    label: "skill value 10"
    input: string
  skill name 11:
    label: "skill name 11"
    input: string
  skill att 11:
    label: "skill att 11"
    input: select
    options:
      physique: physique
      precision: precision
      logic: logic
      empathy: empathy
  skill value 11:
    label: "skill value 11"
    input: string
  skill name 12:
    label: "skill name 12"
    input: string
  skill att 12:
    label: "skill att 12"
    input: select
    options:
      physique: physique
      precision: precision
      logic: logic
      empathy: empathy
  skill value 12:
    label: "skill value 12"
    input: string
  armor name:
    label: "armor name"
    input: string
  armor prot:
    label: "armor prot"
    input: string
  armor agi:
    label: "armor agi"
    input: string
  weapon name 01:
    label: "weapon name 01"
    input: string
  weapon damage 01:
    label: "weapon damage 01"
    input: string
  weapon range 01:
    label: "weapon range 01"
    input: string
  weapon bonus 01:
    label: "weapon bonus 01"
    input: string
  weapon name 02:
    label: "weapon name 02"
    input: string
  weapon damage 02:
    label: "weapon damage 02"
    input: string
  weapon range 02:
    label: "weapon range 02"
    input: string
  weapon bonus 02:
    label: "weapon bonus 02"
    input: string
  weapon name 03:
    label: "weapon name 03"
    input: string
  weapon damage 03:
    label: "weapon damage 03"
    input: string
  weapon range 03:
    label: "weapon range 03"
    input: string
  weapon bonus 03:
    label: "weapon bonus 03"
    input: string
  weapon name 04:
    label: "weapon name 04"
    input: string
  weapon damage 04:
    label: "weapon damage 04"
    input: string
  weapon range 04:
    label: "weapon range 04"
    input: string
  weapon bonus 04:
    label: "weapon bonus 04"
    input: string
  weapon name 05:
    label: "weapon name 05"
    input: string
  weapon damage 05:
    label: "weapon damage 05"
    input: string
  weapon range 05:
    label: "weapon range 05"
    input: string
  weapon bonus 05:
    label: "weapon bonus 05"
    input: string
  notes:
    label: "notes"
    input: text
    rows: 3
