fields:
  agility:
    label: "Agility"
    required: true
    input: integer
    description: "Agility is the measure of your physical and manual dexterity, sense of balance, and body control"
  awareness:
    label: "Awareness"
    required: true
    input: integer
    description: "Awareness represents perception and sense acuity across all five of the key senses: vision, hearing, feeling, taste, and smell"
  brawn:
    label: "Brawn"
    required: true
    input: integer
    description: "Brawn is a measure of might, endurance, toughness, and the physical force you can exert, it determines your close combat damage bonus and the Vigor reserve, the amount of physical injury or stress that you can withstand"
  coordination:
    label: "Coordination"
    required: true
    input: integer
    description: "The Coordination attribute describes hand/eye coordination, aim, and ability to navigate within one's surroundings, both physically and mentally"
  intelligence:
    label: "Intelligence"
    required: true
    input: integer
    description: "Intelligence is the measure of your wit, intellect, and a combination of studies and cunning learned on the streets"
  personality:
    label: "Personality"
    required: true
    input: integer
    description: "Personality is a measure of your charisma, ease of social interaction, and ability to be charming or deceptive as needed. Personality also determines your bonus damage for Threaten actions"
  willpower:
    label: "Willpower"
    required: true
    input: integer
    description: "A person’s force of will, and mental resolve, the Willpower attribute determines your Resolve capacity, the reserve of sanity that prevents mental trauma"
  combat:
    label: "combat"
    input: integer
    description: ""
  fortitude:
    label: "fortitude"
    input: integer
    description: ""
  knowledge:
    label: "knowledge"
    input: integer
    description: ""
  movement:
    label: "movement"
    input: integer
    description: ""
  senses:
    label: "senses"
    input: integer
    description: ""
  social:
    label: "social"
    input: integer
    description: ""
  courage bonus:
    label: "Courage Bonus"
    input: integer
  armour qualities:
    label: "Armour Qualities"
    input: string
  armour soak head:
    label: "Armour Soak Head"
    input: integer
  armour soak rarm:
    label: "Armour Soak RArm"
    input: integer
  armour soak larm:
    label: "Armour Soak LArm"
    input: integer
  armour soak torso:
    label: "Armour Soak Torso"
    input: integer
  armour soak rleg:
    label: "Armour Soak RLeg"
    input: integer
  armour soak lleg:
    label: "Armour Soak LLeg"
    input: integer
  vigor:
    label: "Vigor"
    input: integer
  resolve:
    label: "Resolve"
    input: integer
  wounds:
    label: "Wounds"
    input: integer
  trauma:
    label: "Trauma"
    input: integer
  notes:
    label: "Notes"
    input: text
    rows: 20
  attack name 01:
    label: "Attack Name 01"
    input: string
  attack range 01:
    label: "Attack Range 01"
    input: string
  attack size 01:
    label: "Attack Size 01"
    input: string
  attack damage 01:
    label: "Attack Damage 01"
    input: integer
  attack qualities 01:
    label: "Attack Qualities 01"
    input: string
  attack name 02:
    label: "Attack Name 02"
    input: string
  attack range 02:
    label: "Attack Range 02"
    input: string
  attack size 02:
    label: "Attack Size 02"
    input: string
  attack damage 02:
    label: "Attack Damage 02"
    input: integer
  attack qualities 02:
    label: "Attack Qualities 02"
    input: string