# sheet: blood and doom
fields:
  # row
    # col: col-12 col-md-8
      # card: personal: Personal Information
        # card-body
          # table
  name:
    label: "name"
    input: string
    placeholder: "Name of the hero"
    description: "This is the name of your hero."
    required: true
  player role:
    label: "player role"
    input: string
  class:
    label: "class"
    input: string
  archetype:
    label: "archetype"
    input: string
  origin:
    label: "origin"
    input: string
  silver:
    label: "silver"
    input: integer
  gold:
    label: "gold"
    input: integer
  xp:
    label: "xp"
    input: integer
  level:
    label: "level"
    input: integer
  languages:
    label: "languages"
    input: text
    rows: 3
  deities:
    label: "deities"
    input: text
    rows: 3
          # /table
        # /card-body
      # /card
    # /col
    # col: col-4 col-lg-4 hidden-xs hidden-sm hidden-md d-none d-lg-block
      # card: portrait: Portrait
        # card-body
  portrait:
    label: "portrait"
    input: integer
    render: image
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-6
      # row
        # col: col-12 col-md-4
          # card: attribute: Strength
            # card-body
  strength:
    label: "strength"
    input: string
            # /card-body
          # /card
          # card: attribute: Dexterity
            # card-body
  dexterity:
    label: "dexterity"
    input: string
            # /card-body
          # /card
          # card: attribute: Toughness
            # card-body
  toughness:
    label: "toughness"
    input: string
            # /card-body
          # /card
          # card: attribute: Reflex
            # card-body
  reflex:
    label: "reflex"
    input: string
            # /card-body
          # /card
          # card: attribute: Stealth
            # card-body
  stealth:
    label: "stealth"
    input: string
            # /card-body
          # /card
        # /col
        # col: col-12 col-md-4
          # card: attribute: Intellect 
            # card-body
  intellect:
    label: "intellect"
    input: string
            # /card-body
          # /card
          # card: attribute: Wisdom
            # card-body
  wisdom:
    label: "wisdom"
    input: string
            # /card-body
          # /card
          # card: attribute: Lore
            # card-body
  lore:
    label: "lore"
    input: string
            # /card-body
          # /card
          # card: attribute: Awareness
            # card-body
  awareness:
    label: "awareness"
    input: string
            # /card-body
          # /card
          # card: attribute: Focus
            # card-body
  focus:
    label: "focus"
    input: string
            # /card-body
          # /card
        # /col
        # col: col-12 col-md-4
          # card: attribute: Heart
            # card-body
  heart:
    label: "heart"
    input: string
            # /card-body
          # /card
          # card: attribute: Mystique
            # card-body
  mystique:
    label: "mystique"
    input: string
            # /card-body
          # /card
          # card: attribute: Courage
            # card-body
  courage:
    label: "courage"
    input: string
            # /card-body
          # /card
          # card: attribute: Insight
            # card-body
  insight:
    label: "insight"
    input: string
            # /card-body
          # /card
          # card: attribute: Willpower
            # card-body
  willpower:
    label: "willpower"
    input: string
            # /card-body
          # /card
        # /col
      # /row
    # /col
    # col: col-12 col-md-6
      # card: combat: Combat
        # card-body
          # table: horiz
  doom points:
    label: "doom points"
    input: string
  blood points:
    label: "blood points"
    input: string
          # /table
          # table
  conditions:
    label: "conditions"
    input: string
  afflictions:
    label: "afflictions"
    input: string
  armor:
    label: "armor"
    input: string
  armor durability:
    label: "armor durability"
    input: string
  armor dented:
    label: "armor dented"
    input: string
  armor load:
    label: "armor load"
    input: string
          # /table
          # table: horiz
  armor s value:
    label: "armor s value"
    input: string
  armor c value:
    label: "armor c value"
    input: string
  armor p value:
    label: "armor p value"
    input: string
  armor b value:
    label: "armor b value"
    input: string
  armor e value:
    label: "armor e value"
    input: string
          # /table
          # table
  resilience:
    label: "resilience"
    input: string
  bruises:
    label: "bruises"
    input: string
  wounds:
    label: "wounds"
    input: string
  madness:
    label: "madness"
    input: string
          # /table
          # table: horiz
  charges a:
    label: "charges a"
    input: string
  charges b:
    label: "charges b"
    input: string
  charges c:
    label: "charges c"
    input: string
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-4
      # card: traits: Traits
        # card-body
          # table: horiz
            # iter: 15
  trait name:
    label: "trait name"
    input: string
  trait level:
    label: "trait level"
    input: string
            # /iter
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4
      # card: feats: Feats & Cantrips
        # card-body
  feat:
    label: "feats and cantrips"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4
      # card: magic: Magic
        # card-body
          # table: horiz
            # iter: 15
  magic name:
    label: "magic name"
    input: string
  magic level:
    label: "magic level"
    input: string
  magic bp:
    label: "magic bp"
    input: string
            # /iter
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-6
      # card: combat skills: Combat Skills
        # card-body
          # table: horiz
            # iter: 15
  cskill name:
    label: "cskill name"
    input: string
  cskill level:
    label: "cskill level"
    input: string
            # /iter
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: adventuring skills: Adventuring Skills
        # card-body
          # table: horiz
            # iter: 15
  askill name:
    label: "askill name"
    input: string
  askill level:
    label: "askill level"
    input: string
            # /iter
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-6
      # card: equipment: Equipment
        # card-body
          # table: horiz
            # iter: 15
  equip name:
    label: "equip name"
    input: string
  equip load:
    label: "equip load"
    input: string
  equip dented:
    label: "equip dented"
    input: checkbox
            # /iter
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: consumables: Consumables
        # card-body
          # table: horiz
            # iter: 15
  consum name:
    label: "consum name"
    input: string
  consum load:
    label: "consum load"
    input: string
  consum curr:
    label: "consum curr"
    input: string
  consum max:
    label: "consum max"
    input: string
            # /iter
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-4
      # card: ideals: Ideals
        # card-body
  personality:
    label: "personality"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4
      # card: ideals: Ideals
        # card-body
  ideals:
    label: "ideals"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4
      # card: party vow: Party Vow
        # card-body
  party vow:
    label: "party vow"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4
      # card: habits: Habits
        # card-body
  habits:
    label: "habits"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4
      # card: people: Significant People
        # card-body
  people:
    label: "people"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4
      # card: possession: Cherished Possession
        # card-body
  possession:
    label: "possession"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4
      # card: treasure: Treasure & Trinkets
        # card-body
  treasure:
    label: "treasure"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4
      # card: appearance: Appearance
        # card-body
  appearance:
    label: "appearance"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4
      # card: property: Property & Hirelings
        # card-body
  property:
    label: "property"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4
      # card: notes: Notes
        # card-body
  notes:
    label: "notes"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
  # /row
# /sheet