fields:
# sheet: shadowdark
  # row
    # col: col-12 col-md-5
      # card: personal: Personal
        # card-body
          # table
  name:
    label: "name"
    input: string
  class:
    label: "class"
    input: string
  level:
    label: "level"
    input: integer
  ancestry:
    label: "ancestry"
    input: string
  xp avail:
    label: "xp"
    input: integer
  xp spent:
    label: "xp spent"
    input: integer
  title:
    label: "title"
    input: string
  alignment:
    label: "alignment"
    input: string
  background:
    label: "background"
    input: string
  deity:
    label: "deity"
    input: string
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-3
      # card: attributes: Attributes
        # card-body
          # table
  str:
    label: "str"
    input: integer
  dex:
    label: "dex"
    input: integer
  con:
    label: "con"
    input: integer
  int:
    label: "int"
    input: integer
  wis:
    label: "wis"
    input: integer
  cha:
    label: "cha"
    input: integer
  str mod:
    label: "str mod"
    input: string
  dex mod:
    label: "dex mod"
    input: string
  con mod:
    label: "con mod"
    input: string
  int mod:
    label: "int mod"
    input: string
  wis mod:
    label: "wis mod"
    input: string
  cha mod:
    label: "cha mod"
    input: string
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4
      # card: portrait: Portrait
        # card-body
  portrait:
    render: image
    input: integer
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-3
      # card: hp
        # card-body
          # table
  hp:
    label: "hp"
    input: integer
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-3
      # card: ac
        # card-body
          # table
  ac:
    label: "ac"
    input: integer
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: attacks: Attacks
        # card-body: mention
  attacks:
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-6
      # card: talents: Talents / Spells
        # card-body: mention
  talents:
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: gear: Gear
        # card-body: mention
  gear:
    input: text
    rows: 3
          # table: horiz
  gp:
    label: "gp"
    input: integer
  sp:
    label: "sp"
    input: integer
  cp:
    label: "cp"
    input: integer
          # /table
  free to carry:
    label: "free to carry"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-12
      # card: notes: Notes
        # card-body: mention
  notes:
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
  # /row
# /sheet