# sheet: monster
fields:
  # row
    # col: col-12
      # card: monster: NAMEHERE
        # card-body
  name:
    label: "name"
    input: string
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-6
      # row
        # col: col-4
  str:
    label: "str"
    input: string
        # /col
        # col: col-4
  dex:
    label: "dex"
    input: string
        # /col
        # col: col-4
  tou:
    label: "tou"
    input: string
        # /col
        # col: col-4
  ref:
    label: "ref"
    input: string
        # /col
        # col: col-4
  ste:
    label: "ste"
    input: string
        # /col
      # /row
      # row
        # col: col-4
  int:
    label: "int"
    input: string
        # /col
        # col: col-4
  wis:
    label: "wis"
    input: string
        # /col
        # col: col-4
  lor:
    label: "lor"
    input: string
        # /col
        # col: col-4
  awa:
    label: "awa"
    input: string
        # /col
        # col: col-4
  foc:
    label: "foc"
    input: string
        # /col
      # /row
      # row
        # col: col-4
  hea:
    label: "hea"
    input: string
        # /col
        # col: col-4
  mys:
    label: "mys"
    input: string
        # /col
        # col: col-4
  cou:
    label: "cou"
    input: string
        # /col
        # col: col-4
  ins:
    label: "ins"
    input: string
        # /col
        # col: col-4
  wil:
    label: "wil"
    input: string
        # /col
      # /row
    # /col
    # col: col-12 col-md-6
      # table
  doom points:
    label: "doom points"
    input: integer
  blood points:
    label: "blood points"
    input: integer
  armor:
    label: "armor"
    input: string
  armor values:
    label: "armor values"
    input: string
  size:
    label: "size"
    input: string
  speed:
    label: "speed"
    input: string
  type:
    label: "type"
    input: string
  terrain:
    label: "terrain"
    input: string
      # /table
    # /col
    # col: col-12 col-md-6
      # table
  weapons:
    label: "weapons"
    input: string
  traits:
    label: "traits"
    input: string
  powers:
    label: "powers"
    input: text
    rows: 3
      # /table
    # /col
  # /row
# /sheet