fields:
  name:
    label: "name"
    input: string
    required: true
  imgid:
    label: "imgid"
    input: integer
  form:
    label: "form"
    input: string
    required: true
  type:
    label: "type"
    input: string
    required: true
  size:
    label: "size"
    input: string
    required: true
  location:
    label: "location"
    input: string
  att might:
    label: "att might"
    input: integer
    required: true
  att agility:
    label: "att agility"
    input: integer
    required: true
  att magic:
    label: "att magic"
    input: integer
    required: true
  att heroism:
    label: "att heroism"
    input: integer
    required: true
  heroism points:
    label: "heroism points"
    input: integer
  stealth:
    label: "stealth"
    input: integer
  observation:
    label: "observation"
    input: integer
  speed land:
    label: "speed land"
    input: integer
  speed climb:
    label: "speed climb"
    input: integer
  speed swim:
    label: "speed swim"
    input: integer
  speed fly:
    label: "speed fly"
    input: integer
  speed jump:
    label: "speed jump"
    input: integer
  armor:
    label: "armor"
    input: text
    rows: 3
  weapons:
    label: "weapons"
    input: text
    rows: 3
  strengths:
    label: "strengths"
    input: text
    rows: 3
  skills:
    label: "skills"
    input: text
    rows: 3
  behaviour:
    label: "behaviour"
    input: text
    rows: 3
  actions:
    label: "actions"
    input: text
    rows: 3
  difficulty:
    label: "difficulty"
    input: text
    rows: 3
