fields:
# include: include/header.twig
# include: include/data.twig
# sheet: Laurels and Loot light
  # row
    # col: col-12 col-md-4
  logo:
    label: "Laurels and Loot Logo"
    input: image
    url: /uploads/images/3b0e384be73046581949d1706a0972cd.webp
    # /col
    # col: col-12 col-md-7
      # card: personal
        # card-body
          # table
  name:
    label: "Name"
    input: string
    required: true
  player:
    label: "Player"
    input: string
  parentage:
    label: "Parentage"
    input: select
    options:
      Birdfolk : Birdfolk
      Catfolk : Catfolk
      Dwarf : Dwarf
      Elf : Elf
      Gnome : Gnome
      Goblin : Goblin
      Human : Human
      Halfling : Halfling
      Kobold : Kobold
      Lizardfolk : Lizardfolk
      Orc : Orc
      Ratfolk : Ratfolk      
  occupation:
    label: "Former Occupation"
    input: string
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-1
      # card: level
        # card-body
          # table: horiz
  level:
    label: "Level"
    input: integer
    min: 1
    max: 20
    required: true
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6 col-lg-3
      # card: attributes
        # card-body
          # table
  str:
    label: "STR"
    input: integer
    description: "Strength"
    min: -5
    max: 10
    required: true
  dex:
    label: "DEX"
    input: integer
    description: "Dexterity"
    min: -5
    max: 10
    required: true
  con:
    label: "CON"
    input: integer
    description: "Constitution"
    min: -5
    max: 10
    required: true
  int:
    label: "INT"
    input: integer
    description: "Intelligence"
    min: -5
    max: 10
    required: true
  wis:
    label: "WIS"
    input: integer
    description: "Wisdom"
    min: -5
    max: 10
    required: true
  cha:
    label: "CHA"
    input: integer
    description: "Charisma"
    min: -5
    max: 10
    required: true
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6 col-lg-3
      # card: stamina: Stamina Points
        # card-body
          # table
  stamina sd type:
    label: "SD Type"
    input: select
    options:
      d6: d6
      d8: d8
      d10: d10
  stamina max:
    label: "Maximum"
    input: integer
    min: 0
    max: 300
  stamina curr:
    label: "Current"
    input: integer
    min: 0
    max: 300
          # /table
        # /card-body
      # /card
      # card: injury: Injury Points
        # card-body
          # table
  injury max:
    label: "Maximum"
    input: integer
    min: 0
    max: 20
  injury curr:
    label: "Current"
    input: integer
    min: 0
    max: 20
          # /table
        # /card-body
      # /card
      # card: ap dm
        # card-body
          # table
  ap:
    label: "Armor Points"
    input: integer
    min: -2
    max: 10
  dm:
    label: "Damage Multiple"
    input: integer
    min: 1
    max: 10
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6 col-lg-3
      # card: conditions: Conditions
        # card-body
          # table
  con befuddled:
    label: "Befuddled"
    input: checkbox
  con clumsy:
    label: "Clumsy"
    input: checkbox
  con exhausted:
    label: "Exhausted"
    input: checkbox
  con hastened:
    label: "Hastened"
    input: checkbox
  con paralyzed:
    label: "Paralyzed"
    input: checkbox
  con petrified:
    label: "Petrified"
    input: checkbox
  con prone:
    label: "Prone"
    input: checkbox
  con restrained:
    label: "Restrained"
    input: checkbox
  con slowed:
    label: "Slowed"
    input: checkbox
  con unconscious:
    label: "Unconscious"
    input: checkbox
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6 col-lg-3
      # card: size speed
        # card-body
          # table
  size:
    label: "Size"
    input: string
  speed:
    label: "Speed"
    input: string
          # /table
        # /card-body
      # /card
      # card: specialties: Acquired Specialties
        # card-body
          # table
            # iter: 6
  specialties:
    input: string
            # /iter
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4 col-lg-4
      # card: abilities: Inherent Abilities
        # card-body
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4 col-lg-4
      # card: ability 01
        # card-body
  abilities 01:
    input: string
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4 col-lg-4
      # card: ability 01
        # card-body
  abilities 02:
    input: string
        # /card-body
      # /card
    # /col
    # col: col-12
      # card: coins: Coins
        # card-body
          # row
            # col: col-12 col-md-4
              # table
  coin gold:
    label: "Gold"
    input: string
              # /table
            # /col
            # col: col-12 col-md-4
              # table
  coin silver:
    label: "Silver"
    input: string
              # /table
            # /col
            # col: col-12 col-md-4
              # table
  coin copper:
    label: "Copper"
    input: string
              # /table
            # /col
          # /row
        # /card-body
      # /card
    # /col
    # col: col-12
      # card: inventory: Inventory
        # card-body
          # row
            # col: col-12 col-md-6
              # table: horiz
                # iter: 1: 35
  inventory:
    input: string
  worn:
    input: checkbox
                # /iter
              # /table
            # /col
            # col: col-12 col-md-6
              # table: horiz
                # iter: 36: 70
  inventory:
    input: string
  worn:
    input: checkbox
                # /iter
              # /table
            # /col
          # /row
        # /card-body
      # /card
    # /col
    # col: col-12
      # card: spellbooks: Spellbooks
        # card-body
          # row
            # col: col-12
  sb in use 1:
    label: Spellbook 1
    input: checkbox
            # /col
            # iter: 1: 6
              # col: col-12 col-md-4 col-lg-2
  spell:
    input: string
              # /col
            # /iter
            # col: col-12
  sb in use 2:
    label: Spellbook 2
    input: checkbox
            # /col
            # iter: 7: 12
              # col: col-12 col-md-4 col-lg-2
  spell:
    input: string
              # /col
            # /iter
            # col: col-12
  sb in use 3:
    label: Spellbook 3
    input: checkbox
            # /col
            # iter: 13: 18
              # col: col-12 col-md-4 col-lg-2
  spell:
    input: string
              # /col
            # /iter
            # col: col-12
  sb in use 4:
    label: Spellbook 4
    input: checkbox
            # /col
            # iter: 19: 24
              # col: col-12 col-md-4 col-lg-2
  spell:
    input: string
              # /col
            # /iter
            # col: col-12
  sb in use 5:
    label: Spellbook 5
    input: checkbox
            # /col
            # iter: 25: 30
              # col: col-12 col-md-4 col-lg-2
  spell:
    input: string
              # /col
            # /iter
          # /row
        # /card-body
      # /card
    # /col
    # col: col-12
  possessions:
    label: "Possessions"
    input: string
    # /col
    # col: col-12
      # card: personal
        # card-body
          # row
            # col: col-12 col-md-6
              # table
  physique:
    label: "Physique"
    input: string
  facial features:
    label: "Facial Features"
    input: string
  clothing style:
    label: "Clothing Style"
    input: string
  hair style:
    label: "Hair Style"
    input: string
              # /table
            # /col
            # col: col-12 col-md-6
              # table
  eye color:
    label: "Eye Color"
    input: string
  hair color:
    label: "Hair Color"
    input: string
  skin color:
    label: "Skin Color"
    input: string
  dist marks:
    label: "Distinctive Marks"
    input: string
              # /table
            # /col
          # /row
  physical features:
    label: "Other Physical Features"
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4
      # card: selflessness
        # card-body
          # table: horiz
  selflessness:
    label: "Selflessness"
    input: integer
    min: 0
    max: 10
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4
      # card: respect
        # card-body
          # table: horiz
  respect:
    label: "Respect"
    input: integer
    min: 0
    max: 10
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4
      # card: personality
        # card-body
          # table: horiz
  personality:
    label: "Personality"
    input: string
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-12 col-lg-12
      # card: backstory: Backstory
        # card-body: mention
  backstory:
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-12 col-lg-12
      # card: notes: Journal / Notes
        # card-body: mention
  notes:
    input: text
    rows: 3
        # /card-body
      # /card
    # /col
  # /row
# include: include/footer.twig
# /sheet