# sheet: numenera monster
fields:
  # row
    # col: col-12
      # card: name: name
        # card-body
  name:
    label: "name"
    input: string
    required: true
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-6
      # card: data
        # card-body
          # table
  level:
    label: "level"
    input: integer
  health:
    label: "health"
    input: string
  motive:
    label: "motive"
    input: string
  environment:
    label: "environment"
    input: string
  damage inflicted:
    label: "damage inflicted"
    input: string
  armor:
    label: "armor"
    input: string
  movement:
    label: "movement"
    input: string
  modifications:
    label: "modifications"
    input: string
  combat:
    label: "combat"
    input: text
    rows: 3
  interaction:
    label: "interaction"
    input: text
    rows: 3
  use:
    label: "use"
    input: text
    rows: 3
  loot:
    label: "loot"
    input: string
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: portrait
        # card-body
  imageid:
    label: "imageid"
    input: integer
    render: image
        # /card-body
      # /card
      # card: description
        # card-body
          # table
  description:
    label: "description"
    input: text
    rows: 3
          # /table
        # /card-body
      # /card
    # /col
  # /row
# /sheet