fields:
  name:
    label: "name"
    input: string
  player:
    label: "player"
    input: string
  species:
    label: "species"
    input: string
  action points:
    label: "action points"
    input: string
  action points curr:
    label: "action points curr"
    input: string
  reputation points:
    label: "reputation points"
    input: string
  speed:
    label: "speed"
    input: string
  species benefits:
    label: "species benefits"
    input: string
  languages known:
    label: "languages known"
    input: string
  special abilities:
    label: "special abilities"
    input: text
    rows: 3
  weapon name 01:
    label: "weapon name 01"
    input: string
  weapon range 01:
    label: "weapon range 01"
    input: string
  weapon dmg 01:
    label: "weapon dmg 01"
    input: string
  weapon ammo 01:
    label: "weapon ammo 01"
    input: string
  weapon name 02:
    label: "weapon name 02"
    input: string
  weapon range 02:
    label: "weapon range 02"
    input: string
  weapon dmg 02:
    label: "weapon dmg 02"
    input: string
  weapon ammo 02:
    label: "weapon ammo 02"
    input: string
  weapon name 03:
    label: "weapon name 03"
    input: string
  weapon range 03:
    label: "weapon range 03"
    input: string
  weapon dmg 03:
    label: "weapon dmg 03"
    input: string
  weapon ammo 03:
    label: "weapon ammo 03"
    input: string
  weapon name 04:
    label: "weapon name 04"
    input: string
  weapon range 04:
    label: "weapon range 04"
    input: string
  weapon dmg 04:
    label: "weapon dmg 04"
    input: string
  weapon ammo 04:
    label: "weapon ammo 04"
    input: string
  weapon name 05:
    label: "weapon name 05"
    input: string
  weapon range 05:
    label: "weapon range 05"
    input: string
  weapon dmg 05:
    label: "weapon dmg 05"
    input: string
  weapon ammo 05:
    label: "weapon ammo 05"
    input: string
  weapon name 06:
    label: "weapon name 06"
    input: string
  weapon range 06:
    label: "weapon range 06"
    input: string
  weapon dmg 06:
    label: "weapon dmg 06"
    input: string
  weapon ammo 06:
    label: "weapon ammo 06"
    input: string
  equipment 01:
    label: "equipment 01"
    input: string
  equipment 02:
    label: "equipment 02"
    input: string
  equipment 03:
    label: "equipment 03"
    input: string
  equipment 04:
    label: "equipment 04"
    input: string
  equipment 05:
    label: "equipment 05"
    input: string
  equipment 06:
    label: "equipment 06"
    input: string
  equipment 07:
    label: "equipment 07"
    input: string
  equipment 08:
    label: "equipment 08"
    input: string
  equipment 09:
    label: "equipment 09"
    input: string
  equipment 10:
    label: "equipment 10"
    input: string
  equipment 11:
    label: "equipment 11"
    input: string
  equipment 12:
    label: "equipment 12"
    input: string
  deca credits:
    label: "deca credits"
    input: string
  marks:
    label: "marks"
    input: string
  birthright:
    label: "birthright"
    input: string
  birthright feel:
    label: "birthright feel"
    input: string
  education:
    label: "education"
    input: string
  education feel:
    label: "education feel"
    input: string
  career:
    label: "career"
    input: string
  career feel:
    label: "career feel"
    input: string
  reason:
    label: "reason"
    input: string
  reason feel:
    label: "reason feel"
    input: string
  notes:
    label: "notes"
    input: text
    rows: 3
  imageid:
    label: "imageid"
    input: string
  skill 01:
    label: "skill 01"
    input: checkbox
  skill 02:
    label: "skill 02"
    input: checkbox
  skill 03:
    label: "skill 03"
    input: checkbox
  skill 04:
    label: "skill 04"
    input: checkbox
  skill 05:
    label: "skill 05"
    input: checkbox
  skill 06:
    label: "skill 06"
    input: checkbox
  skill 07:
    label: "skill 07"
    input: checkbox
  skill 08:
    label: "skill 08"
    input: checkbox
  skill 09:
    label: "skill 09"
    input: checkbox
  skill 10:
    label: "skill 10"
    input: checkbox
  skill 11:
    label: "skill 11"
    input: checkbox
  skill 12:
    label: "skill 12"
    input: checkbox
  skill 13:
    label: "skill 13"
    input: checkbox
  skill 14:
    label: "skill 14"
    input: checkbox
  skill 15:
    label: "skill 15"
    input: checkbox
  skill 16:
    label: "skill 16"
    input: checkbox
  skill 17:
    label: "skill 17"
    input: checkbox
  skill 18:
    label: "skill 18"
    input: checkbox
  skill 19:
    label: "skill 19"
    input: checkbox
  skill 20:
    label: "skill 20"
    input: checkbox
  skill 21:
    label: "skill 21"
    input: checkbox
  skill 22:
    label: "skill 22"
    input: checkbox
  skill 23:
    label: "skill 23"
    input: checkbox
  skill 24:
    label: "skill 24"
    input: checkbox
  skill 25:
    label: "skill 25"
    input: checkbox
  skill 26:
    label: "skill 26"
    input: checkbox
  skill 27:
    label: "skill 27"
    input: checkbox
  skill 28:
    label: "skill 28"
    input: checkbox
  skill 29:
    label: "skill 29"
    input: checkbox
  skill 30:
    label: "skill 30"
    input: checkbox
  skill 31:
    label: "skill 31"
    input: checkbox
  skill 32:
    label: "skill 32"
    input: checkbox
  skill 33:
    label: "skill 33"
    input: checkbox
  skill 34:
    label: "skill 34"
    input: checkbox
