fields:
  imageid:
    label: "imageid"
    input: integer
  archetype:
    label: "archetype"
    input: string
    required: true
  level:
    label: "level"
    input: string
  experience:
    label: "experience"
    input: string
  traits physical:
    label: "traits physical"
    placeholder: "eg red glowing eyes"
    input: string
  traits social:
    label: "traits social"
    placeholder: "eg stutters"
    input: string
  secret:
    label: "secret"
    input: string
  description:
    label: "description"
    placeholder: "Race, size and other things"
    input: text
    rows: 3
  attr total:
    label: "attr total"
    input: string
  attr spent:
    label: "attr spent"
    input: string
  hit points curr:
    label: "hit points curr"
    input: string
  hit points mod:
    label: "hit points mod"
    input: string
  legend points:
    label: "legend points"
    input: string
  speed mod:
    label: "speed mod"
    input: string
  wealth level:
    label: "wealth level"
    input: string
  guard mod:
    label: "guard mod"
    input: string
  armor:
    label: "armor"
    input: string
  toughness mod:
    label: "toughness mod"
    input: string
  resolve mod:
    label: "resolve mod"
    input: string
  notes:
    label: "notes"
    input: text
    rows: 3
  equipment:
    label: "equipment"
    input: text
    rows: 3
  perks:
    label: "perks"
    input: text
    rows: 3
  flaws:
    label: "flaws"
    input: text
    rows: 3
  feats total:
    label: "feats total"
    input: string
  feats spent:
    label: "feats spent"
    input: string
  feats:
    label: "feats"
    input: text
    rows: 3
  action name 01:
    label: "action name 01"
    input: string
  action att 01:
    label: "action att 01"
    input: string
  action target 01:
    label: "action target 01"
    input: string
  action dice 01:
    label: "action dice 01"
    input: string
  action special 01:
    label: "action special 01"
    input: string
  action name 02:
    label: "action name 02"
    input: string
  action att 02:
    label: "action att 02"
    input: string
  action target 02:
    label: "action target 02"
    input: string
  action dice 02:
    label: "action dice 02"
    input: string
  action special 02:
    label: "action special 02"
    input: string
  action name 03:
    label: "action name 03"
    input: string
  action att 03:
    label: "action att 03"
    input: string
  action target 03:
    label: "action target 03"
    input: string
  action dice 03:
    label: "action dice 03"
    input: string
  action special 03:
    label: "action special 03"
    input: string
  action name 04:
    label: "action name 04"
    input: string
  action att 04:
    label: "action att 04"
    input: string
  action target 04:
    label: "action target 04"
    input: string
  action dice 04:
    label: "action dice 04"
    input: string
  action special 04:
    label: "action special 04"
    input: string
  action name 05:
    label: "action name 05"
    input: string
  action att 05:
    label: "action att 05"
    input: string
  action target 05:
    label: "action target 05"
    input: string
  action dice 05:
    label: "action dice 05"
    input: string
  action special 05:
    label: "action special 05"
    input: string
  action name 06:
    label: "action name 06"
    input: string
  action att 06:
    label: "action att 06"
    input: string
  action target 06:
    label: "action target 06"
    input: string
  action dice 06:
    label: "action dice 06"
    input: string
  action special 06:
    label: "action special 06"
    input: string
  action name 07:
    label: "action name 07"
    input: string
  action att 07:
    label: "action att 07"
    input: string
  action target 07:
    label: "action target 07"
    input: string
  action dice 07:
    label: "action dice 07"
    input: string
  action special 07:
    label: "action special 07"
    input: string
  action name 08:
    label: "action name 08"
    input: string
  action att 08:
    label: "action att 08"
    input: string
  action target 08:
    label: "action target 08"
    input: string
  action dice 08:
    label: "action dice 08"
    input: string
  action special 08:
    label: "action special 08"
    input: string
  action name 09:
    label: "action name 09"
    input: string
  action att 09:
    label: "action att 09"
    input: string
  action target 09:
    label: "action target 09"
    input: string
  action dice 09:
    label: "action dice 09"
    input: string
  action special 09:
    label: "action special 09"
    input: string
  action name 10:
    label: "action name 10"
    input: string
  action att 10:
    label: "action att 10"
    input: string
  action target 10:
    label: "action target 10"
    input: string
  action dice 10:
    label: "action dice 10"
    input: string
  action special 10:
    label: "action special 10"
    input: string
  action name 11:
    label: "action name 11"
    input: string
  action att 11:
    label: "action att 11"
    input: string
  action target 11:
    label: "action target 11"
    input: string
  action dice 11:
    label: "action dice 11"
    input: string
  action special 11:
    label: "action special 11"
    input: string
  action name 12:
    label: "action name 12"
    input: string
  action att 12:
    label: "action att 12"
    input: string
  action target 12:
    label: "action target 12"
    input: string
  action dice 12:
    label: "action dice 12"
    input: string
  action special 12:
    label: "action special 12"
    input: string
  action name 13:
    label: "action name 13"
    input: string
  action att 13:
    label: "action att 13"
    input: string
  action target 13:
    label: "action target 13"
    input: string
  action dice 13:
    label: "action dice 13"
    input: string
  action special 13:
    label: "action special 13"
    input: string
  action name 14:
    label: "action name 14"
    input: string
  action att 14:
    label: "action att 14"
    input: string
  action target 14:
    label: "action target 14"
    input: string
  action dice 14:
    label: "action dice 14"
    input: string
  action special 14:
    label: "action special 14"
    input: string
  action name 15:
    label: "action name 15"
    input: string
  action att 15:
    label: "action att 15"
    input: string
  action target 15:
    label: "action target 15"
    input: string
  action dice 15:
    label: "action dice 15"
    input: string
  action special 15:
    label: "action special 15"
    input: string
  action name 16:
    label: "action name 16"
    input: string
  action att 16:
    label: "action att 16"
    input: string
  action target 16:
    label: "action target 16"
    input: string
  action dice 16:
    label: "action dice 16"
    input: string
  action special 16:
    label: "action special 16"
    input: string
  action name 17:
    label: "action name 17"
    input: string
  action att 17:
    label: "action att 17"
    input: string
  action target 17:
    label: "action target 17"
    input: string
  action dice 17:
    label: "action dice 17"
    input: string
  action special 17:
    label: "action special 17"
    input: string
  action name 18:
    label: "action name 18"
    input: string
  action att 18:
    label: "action att 18"
    input: string
  action target 18:
    label: "action target 18"
    input: string
  action dice 18:
    label: "action dice 18"
    input: string
  action special 18:
    label: "action special 18"
    input: string
  action name 19:
    label: "action name 19"
    input: string
  action att 19:
    label: "action att 19"
    input: string
  action target 19:
    label: "action target 19"
    input: string
  action dice 19:
    label: "action dice 19"
    input: string
  action special 19:
    label: "action special 19"
    input: string
  action name 20:
    label: "action name 20"
    input: string
  action att 20:
    label: "action att 20"
    input: string
  action target 20:
    label: "action target 20"
    input: string
  action dice 20:
    label: "action dice 20"
    input: string
  action special 20:
    label: "action special 20"
    input: string
  att agility score:
    label: "att agility score"
    input: string
  att agility cost:
    label: "att agility cost"
    input: string
  att agility dice:
    label: "att agility dice"
    input: string
  att fortitude score:
    label: "att fortitude score"
    input: string
  att fortitude cost:
    label: "att fortitude cost"
    input: string
  att fortitude dice:
    label: "att fortitude dice"
    input: string
  att might score:
    label: "att might score"
    input: string
  att might cost:
    label: "att might cost"
    input: string
  att might dice:
    label: "att might dice"
    input: string
  att deception score:
    label: "att deception score"
    input: string
  att deception cost:
    label: "att deception cost"
    input: string
  att deception dice:
    label: "att deception dice"
    input: string
  att presence score:
    label: "att presence score"
    input: string
  att presence cost:
    label: "att presence cost"
    input: string
  att presence dice:
    label: "att presence dice"
    input: string
  att persuation score:
    label: "att persuation score"
    input: string
  att persuation cost:
    label: "att persuation cost"
    input: string
  att persuation dice:
    label: "att persuation dice"
    input: string
  att learning score:
    label: "att learning score"
    input: string
  att learning cost:
    label: "att learning cost"
    input: string
  att learning dice:
    label: "att learning dice"
    input: string
  att logic score:
    label: "att logic score"
    input: string
  att logic cost:
    label: "att logic cost"
    input: string
  att logic dice:
    label: "att logic dice"
    input: string
  att perception score:
    label: "att perception score"
    input: string
  att perception cost:
    label: "att perception cost"
    input: string
  att perception dice:
    label: "att perception dice"
    input: string
  att will score:
    label: "att will score"
    input: string
  att will cost:
    label: "att will cost"
    input: string
  att will dice:
    label: "att will dice"
    input: string
  att alteration score:
    label: "att alteration score"
    input: string
  att alteration cost:
    label: "att alteration cost"
    input: string
  att alteration dice:
    label: "att alteration dice"
    input: string
  att creation score:
    label: "att creation score"
    input: string
  att creation cost:
    label: "att creation cost"
    input: string
  att creation dice:
    label: "att creation dice"
    input: string
  att energy score:
    label: "att energy score"
    input: string
  att energy cost:
    label: "att energy cost"
    input: string
  att energy dice:
    label: "att energy dice"
    input: string
  att entropy score:
    label: "att entropy score"
    input: string
  att entropy cost:
    label: "att entropy cost"
    input: string
  att entropy dice:
    label: "att entropy dice"
    input: string
  att influence score:
    label: "att influence score"
    input: string
  att influence cost:
    label: "att influence cost"
    input: string
  att influence dice:
    label: "att influence dice"
    input: string
  att movement score:
    label: "att movement score"
    input: string
  att movement cost:
    label: "att movement cost"
    input: string
  att movement dice:
    label: "att movement dice"
    input: string
  att prescience score:
    label: "att prescience score"
    input: string
  att prescience cost:
    label: "att prescience cost"
    input: string
  att prescience dice:
    label: "att prescience dice"
    input: string
  att protection score:
    label: "att protection score"
    input: string
  att protection cost:
    label: "att protection cost"
    input: string
  att protection dice:
    label: "att protection dice"
    input: string