fields:
# sheet: MBTI light
  # row
    # col: col-12
      # table: horiz: nosplit
  short:
    label: "Short"
    input: string
    placeholder: "eg ISTJ, INTJ, ..."
  name:
    label: "Display Name"
    input: string
    required: true
    placeholder: "display name"
      # /table
    # /col
  # /row
  # row
    # col: col-12
      # table: horiz: nosplit
  attributes:
    label: "Attributes"
    input: string
    placeholder: "eg introverted, intuitive, judging, ..."
      # /table
    # /col
  # /row
  # row
    # col: col-12
  short desc:
    label: "Short description"
    input: text
    rows: 3
    # /col
  # /row
  # row
    # col: col-12
  long desc:
    label: "Long description"
    input: text
    rows: 3
    # /col
  # /row
# /sheet