fields:
  name:
    label: "name"
    input: string
  class:
    label: "class"
    input: string
  hull pp:
    label: "hull pp"
    input: string
  cost:
    label: "cost"
    input: string
  length:
    label: "length"
    input: string
  width:
    label: "width"
    input: string
  depth:
    label: "depth"
    input: string
  crew min:
    label: "crew min"
    input: string
  crew max:
    label: "crew max"
    input: string
  crew curr:
    label: "crew curr"
    input: string
  upkeep:
    label: "upkeep"
    input: string
  salary:
    label: "salary"
    input: string
  cargo max:
    label: "cargo max"
    input: string
  cargo curr:
    label: "cargo curr"
    input: string
  cargo:
    label: "cargo"
    input: text
    rows: 3
  npc captain:
    label: "npc captain"
    input: string
  npc helmsman:
    label: "npc helmsman"
    input: string
  npc tactical:
    label: "npc tactical"
    input: string
  npc engineer:
    label: "npc engineer"
    input: string
  cmp comm max pp:
    label: "cmp comm max pp"
    input: string
  cmp counter max pp:
    label: "cmp counter max pp"
    input: string
  cmp dive engine max pp:
    label: "cmp dive engine max pp"
    input: string
  cmp navigation max pp:
    label: "cmp navigation max pp"
    input: string
  cmp life support max pp:
    label: "cmp life support max pp"
    input: string
  cmp scanners max pp:
    label: "cmp scanners max pp"
    input: string
  cmp transponder max pp:
    label: "cmp transponder max pp"
    input: string
  cmp comm curr pp:
    label: "cmp comm curr pp"
    input: string
  cmp counter curr pp:
    label: "cmp counter curr pp"
    input: string
  cmp dive engine curr pp:
    label: "cmp dive engine curr pp"
    input: string
  cmp navigation curr pp:
    label: "cmp navigation curr pp"
    input: string
  cmp life support curr pp:
    label: "cmp life support curr pp"
    input: string
  cmp scanners curr pp:
    label: "cmp scanners curr pp"
    input: string
  cmp transponder curr pp:
    label: "cmp transponder curr pp"
    input: string
  ship portrait:
    label: "ship portrait"
    input: string
  wpn max pp 01:
    label: "wpn max pp 01"
    input: string
  wpn curr pp 01:
    label: "wpn curr pp 01"
    input: string
  wpn array 01:
    label: "wpn system 01"
    input: string
  wpn desc 01:
    label: "wpn desc 01"
    input: string
  wpn min target 01:
    label: "wpn min target 01"
    input: string
  wpn range 01:
    label: "wpn range 01"
    input: string
  wpn damage 01:
    label: "wpn damage 01"
    input: string
  wpn x2 pp 01:
    label: "wpn x2 pp 01"
    input: string
  wpn max pp 02:
    label: "wpn max pp 02"
    input: string
  wpn curr pp 02:
    label: "wpn curr pp 02"
    input: string
  wpn array 02:
    label: "wpn system 02"
    input: string
  wpn desc 02:
    label: "wpn desc 02"
    input: string
  wpn min target 02:
    label: "wpn min target 02"
    input: string
  wpn range 02:
    label: "wpn range 02"
    input: string
  wpn damage 02:
    label: "wpn damage 02"
    input: string
  wpn x2 pp 02:
    label: "wpn x2 pp 02"
    input: string
  wpn max pp 03:
    label: "wpn max pp 03"
    input: string
  wpn curr pp 03:
    label: "wpn curr pp 03"
    input: string
  wpn array 03:
    label: "wpn system 03"
    input: string
  wpn desc 03:
    label: "wpn desc 03"
    input: string
  wpn min target 03:
    label: "wpn min target 03"
    input: string
  wpn range 03:
    label: "wpn range 03"
    input: string
  wpn damage 03:
    label: "wpn damage 03"
    input: string
  wpn x2 pp 03:
    label: "wpn x2 pp 03"
    input: string
  wpn max pp 04:
    label: "wpn max pp 04"
    input: string
  wpn curr pp 04:
    label: "wpn curr pp 04"
    input: string
  wpn array 04:
    label: "wpn system 04"
    input: string
  wpn desc 04:
    label: "wpn desc 04"
    input: string
  wpn min target 04:
    label: "wpn min target 04"
    input: string
  wpn range 04:
    label: "wpn range 04"
    input: string
  wpn damage 04:
    label: "wpn damage 04"
    input: string
  wpn x2 pp 04:
    label: "wpn x2 pp 04"
    input: string
  wpn max pp 05:
    label: "wpn max pp 05"
    input: string
  wpn curr pp 05:
    label: "wpn curr pp 05"
    input: string
  wpn array 05:
    label: "wpn system 05"
    input: string
  wpn desc 05:
    label: "wpn desc 05"
    input: string
  wpn min target 05:
    label: "wpn min target 05"
    input: string
  wpn range 05:
    label: "wpn range 05"
    input: string
  wpn damage 05:
    label: "wpn damage 05"
    input: string
  wpn x2 pp 05:
    label: "wpn x2 pp 05"
    input: string
  wpn max pp 06:
    label: "wpn max pp 06"
    input: string
  wpn curr pp 06:
    label: "wpn curr pp 06"
    input: string
  wpn array 06:
    label: "wpn system 06"
    input: string
  wpn desc 06:
    label: "wpn desc 06"
    input: string
  wpn min target 06:
    label: "wpn min target 06"
    input: string
  wpn range 06:
    label: "wpn range 06"
    input: string
  wpn damage 06:
    label: "wpn damage 06"
    input: string
  wpn x2 pp 06:
    label: "wpn x2 pp 06"
    input: string
  wpn max pp 07:
    label: "wpn max pp 07"
    input: string
  wpn curr pp 07:
    label: "wpn curr pp 07"
    input: string
  wpn array 07:
    label: "wpn system 07"
    input: string
  wpn desc 07:
    label: "wpn desc 07"
    input: string
  wpn min target 07:
    label: "wpn min target 07"
    input: string
  wpn range 07:
    label: "wpn range 07"
    input: string
  wpn damage 07:
    label: "wpn damage 07"
    input: string
  wpn x2 pp 07:
    label: "wpn x2 pp 07"
    input: string
  wpn max pp 08:
    label: "wpn max pp 08"
    input: string
  wpn curr pp 08:
    label: "wpn curr pp 08"
    input: string
  wpn array 08:
    label: "wpn system 08"
    input: string
  wpn desc 08:
    label: "wpn desc 08"
    input: string
  wpn min target 08:
    label: "wpn min target 08"
    input: string
  wpn range 08:
    label: "wpn range 08"
    input: string
  wpn damage 08:
    label: "wpn damage 08"
    input: string
  wpn x2 pp 08:
    label: "wpn x2 pp 08"
    input: string
  wpn max pp 09:
    label: "wpn max pp 09"
    input: string
  wpn curr pp 09:
    label: "wpn curr pp 09"
    input: string
  wpn array 09:
    label: "wpn system 09"
    input: string
  wpn desc 09:
    label: "wpn desc 09"
    input: string
  wpn min target 09:
    label: "wpn min target 09"
    input: string
  wpn range 09:
    label: "wpn range 09"
    input: string
  wpn damage 09:
    label: "wpn damage 09"
    input: string
  wpn x2 pp 09:
    label: "wpn x2 pp 09"
    input: string
  wpn max pp 10:
    label: "wpn max pp 10"
    input: string
  wpn curr pp 10:
    label: "wpn curr pp 10"
    input: string
  wpn array 10:
    label: "wpn system 10"
    input: string
  wpn desc 10:
    label: "wpn desc 10"
    input: string
  wpn min target 10:
    label: "wpn min target 10"
    input: string
  wpn range 10:
    label: "wpn range 10"
    input: string
  wpn damage 10:
    label: "wpn damage 10"
    input: string
  wpn x2 pp 10:
    label: "wpn x2 pp 10"
    input: string
  wpn max pp 11:
    label: "wpn max pp 11"
    input: string
  wpn curr pp 11:
    label: "wpn curr pp 11"
    input: string
  wpn array 11:
    label: "wpn system 11"
    input: string
  wpn desc 11:
    label: "wpn desc 11"
    input: string
  wpn min target 11:
    label: "wpn min target 11"
    input: string
  wpn range 11:
    label: "wpn range 11"
    input: string
  wpn damage 11:
    label: "wpn damage 11"
    input: string
  wpn x2 pp 11:
    label: "wpn x2 pp 11"
    input: string
  wpn max pp 12:
    label: "wpn max pp 12"
    input: string
  wpn curr pp 12:
    label: "wpn curr pp 12"
    input: string
  wpn array 12:
    label: "wpn system 12"
    input: string
  wpn desc 12:
    label: "wpn desc 12"
    input: string
  wpn min target 12:
    label: "wpn min target 12"
    input: string
  wpn range 12:
    label: "wpn range 12"
    input: string
  wpn damage 12:
    label: "wpn damage 12"
    input: string
  wpn x2 pp 12:
    label: "wpn x2 pp 12"
    input: string
  wpn max pp 13:
    label: "wpn max pp 13"
    input: string
  wpn curr pp 13:
    label: "wpn curr pp 13"
    input: string
  wpn array 13:
    label: "wpn system 13"
    input: string
  wpn desc 13:
    label: "wpn desc 13"
    input: string
  wpn min target 13:
    label: "wpn min target 13"
    input: string
  wpn range 13:
    label: "wpn range 13"
    input: string
  wpn damage 13:
    label: "wpn damage 13"
    input: string
  wpn x2 pp 13:
    label: "wpn x2 pp 13"
    input: string
  wpn max pp 14:
    label: "wpn max pp 14"
    input: string
  wpn curr pp 14:
    label: "wpn curr pp 14"
    input: string
  wpn array 14:
    label: "wpn system 14"
    input: string
  wpn desc 14:
    label: "wpn desc 14"
    input: string
  wpn min target 14:
    label: "wpn min target 14"
    input: string
  wpn range 14:
    label: "wpn range 14"
    input: string
  wpn damage 14:
    label: "wpn damage 14"
    input: string
  wpn x2 pp 14:
    label: "wpn x2 pp 14"
    input: string
  wpn max pp 15:
    label: "wpn max pp 15"
    input: string
  wpn curr pp 15:
    label: "wpn curr pp 15"
    input: string
  wpn array 15:
    label: "wpn system 15"
    input: string
  wpn desc 15:
    label: "wpn desc 15"
    input: string
  wpn min target 15:
    label: "wpn min target 15"
    input: string
  wpn range 15:
    label: "wpn range 15"
    input: string
  wpn damage 15:
    label: "wpn damage 15"
    input: string
  wpn x2 pp 15:
    label: "wpn x2 pp 15"
    input: string
  notes:
    label: "notes"
    input: text
    rows: 3
