fields:
# sheet: NycosRPG
  # row
    # col: col-12 col-md-6
  text:
    label: DARK SHARDS
    style: h1
  text:
    label: PERSONA CREATION WORKSHEET
    style: h4
      # row
        # col: col-12 col-md-4
  text:
    label: "NAME"
        # /col
        # col: col-12 col-md-8 box1
  name:
    input: string
        # /col
      # /row
    # /col
    # col: col-12 col-md-6 d-none d-md-block d-lg-block logo
  image:
    label: "NycosRPG"
    url: /uploads/images/7f40cc6fdeb25508a29ca7bf1806c54f.webp
    width: 320px
    # /col
  # /row
  # br
  # row
    # col: col-12
      # card: basics
        # card-body
          # row
            # col: col-12 col-md-6
              # row
                # col: col-6 mainlbl
  text:
    label: BASE
    style: h3
                # /col
                # col: col-3 bclbl
  text:
    label: BASE
    style: h3
                # /col
                # col: col-3 bclbl
  text:
    label: CORE
    style: h3
                # /col
              # /row
              # row
                # col: col-6 attlbl
  text:
    label: BRILLIANCE
    style: h4
                # /col
                # col: col-3 attb
  base brilliance:
    input: integer
                # /col
                # col: col-3 attc
  core brilliance:
    input: integer
                # /col
              # /row
              # row
                # col: col-6 attlbl
  text:
    label: COGNIZANCE
    style: h4
                # /col
                # col: col-3 attb
  base cognizance:
    input: integer
                # /col
                # col: col-3 attc
  core cognizance:
    input: integer
                # /col
              # /row
              # row
                # col: col-6 attlbl
  text:
    label: GRACE
    style: h4
                # /col
                # col: col-3 attb
  base grace:
    input: integer
                # /col
                # col: col-3 attc
  core grace:
    input: integer
                # /col
              # /row
              # row
                # col: col-6 attlbl
  text:
    label: PRESENCE
    style: h4
                # /col
                # col: col-3 attb
  base presence:
    input: integer
                # /col
                # col: col-3 attc
  core presence:
    input: integer
                # /col
              # /row
              # row
                # col: col-6 attlbl
  text:
    label: RESILIENCE
    style: h4
                # /col
                # col: col-3 attb
  base resilience:
    input: integer
                # /col
                # col: col-3 attc
  core resilience:
    input: integer
                # /col
              # /row
              # row
                # col: col-6 attlbl
  text:
    label: RESOLVE
    style: h4
                # /col
                # col: col-3 attb
  base resolve:
    input: integer
                # /col
                # col: col-3 attc
  core resolve:
    input: integer
                # /col
              # /row
              # row
                # col: col-6 attlbl
  text:
    label: FOUNDATION
    style: h4
                # /col
                # col: col-3 attb
  base foundation:
    input: integer
                # /col
                # col: col-3 attc
  core foundation:
    input: integer
                # /col
              # /row
            # /col
            # col: col-12 col-md-6
              # row
                # col: col-4 mainlbl
  text:
    label: RACE
    style: h3
                # /col
                # col: col-8 box1
  race:
    input: string
                # /col
              # /row
              # br
              # row
                # col: col-3 listhdr race
  text:
    label: "MARK VALUE"
                # /col
                # col: col-9 listhdr race
  text:
    label: "NAME OF THE MARK"
                # /col
              # /row
              # row
                # iter: 6
                  # col: col-3 box1
  mark value:
    input: integer
                  # /col
                  # col: col-9 box1
  mark desc:
    input: string
                  # /col
                # /iter
              # /row
            # /col
          # /row
        # /card-body
      # /card
    # /col
  # /row
  # br
  # row
    # col: col-12
      # card: place and estate
        # card-body
          # row
            # col: col-12 col-md-6
              # row
                # col: col-4 mainlbl
  text:
    label: "PLACE"
    style: h3
                # /col
                # col: col-8 box1
  place:
    input: string
                # /col
              # /row
              # br
              # row
                # col: col-3 listhdr place
  text:
    label: "SKILL VALUE"
                # /col
                # col: col-9 listhdr place
  text:
    label: "DESCRIPTION OF THE SKILLS"
                # /col
              # /row
              # row
                # iter: 1: 4
                  # col: col-3 box1
  skill value:
    input: integer
                  # /col
                  # col: col-9 box1
  skill desc:
    input: string
                  # /col
                # /iter
              # /row
            # /col
            # col: col-12 col-md-6
              # row
                # col: col-4 mainlbl
  text:
    label: "ESTATE"
    style: h3
                # /col
                # col: col-8 box1
  estate:
    input: string
                # /col
              # /row
              # br
              # row
                # col: col-3 listhdr estate
  text:
    label: "SKILL VALUE"
                # /col
                # col: col-9 listhdr estate
  text:
    label: "DESCRIPTION OF THE SKILLS"
                # /col
              # /row
              # row
                # iter: 5: 8
                  # col: col-3 box1
  skill value:
    input: integer
                  # /col
                  # col: col-9 box1
  skill desc:
    input: string
                  # /col
                # /iter
              # /row
            # /col
          # /row
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: basics
        # card-body
          # row
            # col: col-12
  text:
    label: "OPERATIONAL SKILLS"
    style: "h2"
            # /col
            # col: col-12 col-md-4
              # row
                # col: col-3 listhdr oskills
  text:
    label: "BASE"
                # /col
                # col: col-9 listhdr oskills
  text:
    label: "SKILL NAME"
                # /col
              # /row
            # /col
            # col: col-12 col-md-4 d-none d-md-block d-lg-block
              # row
                # col: col-3 listhdr oskills
  text:
    label: "BASE"
                # /col
                # col: col-9 listhdr oskills
  text:
    label: "SKILL NAME"
                # /col
              # /row
            # /col
            # col: col-12 col-md-4 d-none d-md-block d-lg-block
              # row
                # col: col-3 listhdr oskills
  text:
    label: "BASE"
                # /col
                # col: col-9 listhdr oskills
  text:
    label: "SKILL NAME"
                # /col
              # /row
            # /col
            # iter: 48
              # col: col-12 col-md-4
                # row
                  # col: col-3 box1
  opskill value:
    input: integer
                  # /col
                  # col: col-9 box1
  opskill name:
    input: string
                  # /col
                # /row
              # /col
            # /iter
          # /row
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: basics
        # card-body
          # row
            # col: col-12
  text:
    label: "TRAINING IN PROGRESS"
    style: "h2"
            # /col
            # iter: 6
              # col: col-12 col-md-4
                # row
                  # col: col-3 box1
  training value:
    input: integer
                  # /col
                  # col: col-9 box1
  training name:
    input: string
                  # /col
                # /row
              # /col
            # /iter
          # /row
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: basics
        # card-body
          # row
            # col: col-12
  text:
    label: "LEARNING IN PROGRESS"
    style: "h2"
            # /col
            # iter: 9
              # col: col-12 col-md-4
                # row
                  # col: col-3 box1
  learning value:
    input: integer
                  # /col
                  # col: col-9 box1
  learning name:
    input: string
                  # /col
                # /row
              # /col
            # /iter
          # /row
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: basics
        # card-body
          # row
            # col: col-12
  text:
    label: "INVENTORY OF STUFF"
    style: "h2"
            # /col
            # iter: 30
              # col: col-12 col-md-4
                # row
                  # col: col-3 box1
  inventory value:
    input: integer
                  # /col
                  # col: col-9 box1
  inventory name:
    input: string
                  # /col
                # /row
              # /col
            # /iter
          # /row
        # /card-body
      # /card
    # /col
  # /row
# /sheet