fields:
  player name:
    label: "player name"
    input: string
    required: true
  image id:
    label: "image id"
    input: integer
  age:
    label: "age"
    input: string
  height:
    label: "height"
    input: string
  weight:
    label: "weight"
    input: string
  eyes:
    label: "eyes"
    input: string
  hair:
    label: "hair"
    input: string
  description:
    label: "description"
    input: text
    rows: 3
  ancestry:
    label: "ancestry"
    input: string
    required: true
  background:
    label: "background"
    input: string
    required: true
  class:
    label: "class"
    input: select
    required: true
    options:
      Assassin: Assassin
      Druid: Druid
      Minstrel: Minstrel
      Priest: Priest
      Prophet: Prophet
      Sorcerer: Sorcerer
      Warrior: Warrior
      Wizard: Wizard
  level:
    label: "level"
    input: integer
    min: 1
    required: true
  xp:
    label: "xp"
    input: integer
  alignment:
    label: "alignment"
    input: select
    required: true
    options:
      neutral: neutral
      good: good
      evil: evil
  strength:
    label: "strength"
    input: string
    required: true
  brawn:
    label: "brawn"
    input: integer
    required: true
  agility:
    label: "agility"
    input: integer
    required: true
  mettle:
    label: "mettle"
    input: integer
    required: true
  craft:
    label: "craft"
    input: integer
    required: true
  insight:
    label: "insight"
    input: integer
    required: true
  wits:
    label: "wits"
    input: integer
    required: true
  resolve:
    label: "resolve"
    input: integer
    required: true
  recover curr:
    label: "recover curr"
    input: string
  special abilities:
    label: "special abilities"
    input: text
    rows: 3
  phys dmg mod:
    label: "phys dmg mod"
    input: string
  psych dmg mod:
    label: "psych dmg mod"
    input: string
  life curr:
    label: "life curr"
    input: string
  life:
    label: "life"
    input: string
    required: true
  light fate:
    label: "light fate"
    input: string
  arm helm:
    label: "arm helm"
    input: checkbox
  arm shield:
    label: "arm shield"
    input: checkbox
  arm type:
    label: "arm type"
    input: select
    options:
      Clothes: Clothes
      Leather: Leather
      Hard Leather: Hard Leather
      Chain: Chain
      Mail: Mail
      Plate: Plate
  arm points curr:
    label: "arm points curr"
    input: integer
    min: 0
    max: 24
  wounds:
    label: "wounds"
    input: integer
    min: 0
    max: 5
  death tests:
    label: "death tests"
    input: integer
    min: 0
    max: 5
  followers:
    label: "followers"
    input: text
    rows: 3
  spell points curr:
    label: "spell points curr"
    input: string
  spell points:
    label: "spell points"
    input: string
  magic items:
    label: "magic items"
    input: text
    rows: 3
  gold:
    label: "gold"
    input: string
  equip name 01:
    label: "equip name 01"
    input: string
  equip load 01:
    label: "equip load 01"
    input: string
  equip name 02:
    label: "equip name 02"
    input: string
  equip load 02:
    label: "equip load 02"
    input: string
  equip name 03:
    label: "equip name 03"
    input: string
  equip load 03:
    label: "equip load 03"
    input: string
  equip name 04:
    label: "equip name 04"
    input: string
  equip load 04:
    label: "equip load 04"
    input: string
  equip name 05:
    label: "equip name 05"
    input: string
  equip load 05:
    label: "equip load 05"
    input: string
  equip name 06:
    label: "equip name 06"
    input: string
  equip load 06:
    label: "equip load 06"
    input: string
  equip name 07:
    label: "equip name 07"
    input: string
  equip load 07:
    label: "equip load 07"
    input: string
  equip name 08:
    label: "equip name 08"
    input: string
  equip load 08:
    label: "equip load 08"
    input: string
  equip name 09:
    label: "equip name 09"
    input: string
  equip load 09:
    label: "equip load 09"
    input: string
  equip name 10:
    label: "equip name 10"
    input: string
  equip load 10:
    label: "equip load 10"
    input: string
  equip name 11:
    label: "equip name 11"
    input: string
  equip load 11:
    label: "equip load 11"
    input: string
  equip name 12:
    label: "equip name 12"
    input: string
  equip load 12:
    label: "equip load 12"
    input: string
  equip name 13:
    label: "equip name 13"
    input: string
  equip load 13:
    label: "equip load 13"
    input: string
  equip name 14:
    label: "equip name 14"
    input: string
  equip load 14:
    label: "equip load 14"
    input: string
  equip name 15:
    label: "equip name 15"
    input: string
  equip load 15:
    label: "equip load 15"
    input: string
  equip name 16:
    label: "equip name 16"
    input: string
  equip load 16:
    label: "equip load 16"
    input: string
  equip name 17:
    label: "equip name 17"
    input: string
  equip load 17:
    label: "equip load 17"
    input: string
  equip name 18:
    label: "equip name 18"
    input: string
  equip load 18:
    label: "equip load 18"
    input: string
  equip name 19:
    label: "equip name 19"
    input: string
  equip load 19:
    label: "equip load 19"
    input: string
  equip name 20:
    label: "equip name 20"
    input: string
  equip load 20:
    label: "equip load 20"
    input: string
  equip name 21:
    label: "equip name 21"
    input: string
  equip load 21:
    label: "equip load 21"
    input: string
  equip name 22:
    label: "equip name 22"
    input: string
  equip load 22:
    label: "equip load 22"
    input: string
  equip name 23:
    label: "equip name 23"
    input: string
  equip load 23:
    label: "equip load 23"
    input: string
  equip name 24:
    label: "equip name 24"
    input: string
  equip load 24:
    label: "equip load 24"
    input: string
  equip name 25:
    label: "equip name 25"
    input: string
  equip load 25:
    label: "equip load 25"
    input: string
  equip name 26:
    label: "equip name 26"
    input: string
  equip load 26:
    label: "equip load 26"
    input: string
  equip name 27:
    label: "equip name 27"
    input: string
  equip load 27:
    label: "equip load 27"
    input: string
  equip name 28:
    label: "equip name 28"
    input: string
  equip load 28:
    label: "equip load 28"
    input: string
  equip name 29:
    label: "equip name 29"
    input: string
  equip load 29:
    label: "equip load 29"
    input: string
  equip name 30:
    label: "equip name 30"
    input: string
  equip load 30:
    label: "equip load 30"
    input: string
  weapon name 01:
    label: "weapon name 01"
    input: string
  weapon att bonus 01:
    label: "weapon att bonus 01"
    input: string
  weapon damage 01:
    label: "weapon damage 01"
    input: string
  weapon name 02:
    label: "weapon name 02"
    input: string
  weapon att bonus 02:
    label: "weapon att bonus 02"
    input: string
  weapon damage 02:
    label: "weapon damage 02"
    input: string
  weapon name 03:
    label: "weapon name 03"
    input: string
  weapon att bonus 03:
    label: "weapon att bonus 03"
    input: string
  weapon damage 03:
    label: "weapon damage 03"
    input: string
  weapon name 04:
    label: "weapon name 04"
    input: string
  weapon att bonus 04:
    label: "weapon att bonus 04"
    input: string
  weapon damage 04:
    label: "weapon damage 04"
    input: string
  weapon name 05:
    label: "weapon name 05"
    input: string
  weapon att bonus 05:
    label: "weapon att bonus 05"
    input: string
  weapon damage 05:
    label: "weapon damage 05"
    input: string
  weapon name 06:
    label: "weapon name 06"
    input: string
  weapon att bonus 06:
    label: "weapon att bonus 06"
    input: string
  weapon damage 06:
    label: "weapon damage 06"
    input: string
  weapon name 07:
    label: "weapon name 07"
    input: string
  weapon att bonus 07:
    label: "weapon att bonus 07"
    input: string
  weapon damage 07:
    label: "weapon damage 07"
    input: string
  weapon name 08:
    label: "weapon name 08"
    input: string
  weapon att bonus 08:
    label: "weapon att bonus 08"
    input: string
  weapon damage 08:
    label: "weapon damage 08"
    input: string
  weapon name 09:
    label: "weapon name 09"
    input: string
  weapon att bonus 09:
    label: "weapon att bonus 09"
    input: string
  weapon damage 09:
    label: "weapon damage 09"
    input: string
  weapon name 10:
    label: "weapon name 10"
    input: string
  weapon att bonus 10:
    label: "weapon att bonus 10"
    input: string
  weapon damage 10:
    label: "weapon damage 10"
    input: string
  spells:
    label: "spells"
    input: text
    rows: 3
  notes:
    label: "notes"
    input: text
    rows: 3
  skill focuses 01:
    label: "skill focuses 01"
    input: string
  skill learned 01:
    label: "skill learned 01"
    input: checkbox
  skill focuses 02:
    label: "skill focuses 02"
    input: string
  skill learned 02:
    label: "skill learned 02"
    input: checkbox
  skill focuses 03:
    label: "skill focuses 03"
    input: string
  skill learned 03:
    label: "skill learned 03"
    input: checkbox
  skill focuses 04:
    label: "skill focuses 04"
    input: string
  skill learned 04:
    label: "skill learned 04"
    input: checkbox
  skill focuses 05:
    label: "skill focuses 05"
    input: string
  skill learned 05:
    label: "skill learned 05"
    input: checkbox
  skill focuses 06:
    label: "skill focuses 06"
    input: string
  skill learned 06:
    label: "skill learned 06"
    input: checkbox
  skill focuses 07:
    label: "skill focuses 07"
    input: string
  skill learned 07:
    label: "skill learned 07"
    input: checkbox
  skill focuses 08:
    label: "skill focuses 08"
    input: string
  skill learned 08:
    label: "skill learned 08"
    input: checkbox
  skill focuses 09:
    label: "skill focuses 09"
    input: string
  skill learned 09:
    label: "skill learned 09"
    input: checkbox
  skill focuses 10:
    label: "skill focuses 10"
    input: string
  skill learned 10:
    label: "skill learned 10"
    input: checkbox
  skill focuses 11:
    label: "skill focuses 11"
    input: string
  skill learned 11:
    label: "skill learned 11"
    input: checkbox
  skill focuses 12:
    label: "skill focuses 12"
    input: string
  skill learned 12:
    label: "skill learned 12"
    input: checkbox
  skill focuses 13:
    label: "skill focuses 13"
    input: string
  skill learned 13:
    label: "skill learned 13"
    input: checkbox
  skill focuses 14:
    label: "skill focuses 14"
    input: string
  skill learned 14:
    label: "skill learned 14"
    input: checkbox
  skill focuses 15:
    label: "skill focuses 15"
    input: string
  skill learned 15:
    label: "skill learned 15"
    input: checkbox
  skill focuses 16:
    label: "skill focuses 16"
    input: string
  skill learned 16:
    label: "skill learned 16"
    input: checkbox
  skill focuses 17:
    label: "skill focuses 17"
    input: string
  skill learned 17:
    label: "skill learned 17"
    input: checkbox
  skill focuses 18:
    label: "skill focuses 18"
    input: string
  skill learned 18:
    label: "skill learned 18"
    input: checkbox
  skill focuses 19:
    label: "skill focuses 19"
    input: string
  skill learned 19:
    label: "skill learned 19"
    input: checkbox
  skill focuses 20:
    label: "skill focuses 20"
    input: string
  skill learned 20:
    label: "skill learned 20"
    input: checkbox
  skill focuses 21:
    label: "skill focuses 21"
    input: string
  skill learned 21:
    label: "skill learned 21"
    input: checkbox
  skill focuses 22:
    label: "skill focuses 22"
    input: string
  skill learned 22:
    label: "skill learned 22"
    input: checkbox
  skill focuses 23:
    label: "skill focuses 23"
    input: string
  skill learned 23:
    label: "skill learned 23"
    input: checkbox
  skill focuses 24:
    label: "skill focuses 24"
    input: string
  skill learned 24:
    label: "skill learned 24"
    input: checkbox
  skill focuses 25:
    label: "skill focuses 25"
    input: string
  skill learned 25:
    label: "skill learned 25"
    input: checkbox
  skill focuses 26:
    label: "skill focuses 26"
    input: string
  skill learned 26:
    label: "skill learned 26"
    input: checkbox
